// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
)

// Defines values for AgentCertificateRecoveryGrantStatus.
const (
	AgentCertificateRecoveryGrantStatusAllowed AgentCertificateRecoveryGrantStatus = "allowed"
	AgentCertificateRecoveryGrantStatusExpired AgentCertificateRecoveryGrantStatus = "expired"
	AgentCertificateRecoveryGrantStatusRevoked AgentCertificateRecoveryGrantStatus = "revoked"
	AgentCertificateRecoveryGrantStatusUsed    AgentCertificateRecoveryGrantStatus = "used"
)

// Valid indicates whether the value is a known member of the AgentCertificateRecoveryGrantStatus enum.
func (e AgentCertificateRecoveryGrantStatus) Valid() bool {
	switch e {
	case AgentCertificateRecoveryGrantStatusAllowed:
		return true
	case AgentCertificateRecoveryGrantStatusExpired:
		return true
	case AgentCertificateRecoveryGrantStatusRevoked:
		return true
	case AgentCertificateRecoveryGrantStatusUsed:
		return true
	default:
		return false
	}
}

// Defines values for EnrollmentTokenListItemStatus.
const (
	EnrollmentTokenListItemStatusActive   EnrollmentTokenListItemStatus = "active"
	EnrollmentTokenListItemStatusConsumed EnrollmentTokenListItemStatus = "consumed"
	EnrollmentTokenListItemStatusExpired  EnrollmentTokenListItemStatus = "expired"
	EnrollmentTokenListItemStatusRevoked  EnrollmentTokenListItemStatus = "revoked"
)

// Valid indicates whether the value is a known member of the EnrollmentTokenListItemStatus enum.
func (e EnrollmentTokenListItemStatus) Valid() bool {
	switch e {
	case EnrollmentTokenListItemStatusActive:
		return true
	case EnrollmentTokenListItemStatusConsumed:
		return true
	case EnrollmentTokenListItemStatusExpired:
		return true
	case EnrollmentTokenListItemStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAgentTransportModeRequestTransportMode.
const (
	Inbound  UpdateAgentTransportModeRequestTransportMode = "inbound"
	Outbound UpdateAgentTransportModeRequestTransportMode = "outbound"
)

// Valid indicates whether the value is a known member of the UpdateAgentTransportModeRequestTransportMode enum.
func (e UpdateAgentTransportModeRequestTransportMode) Valid() bool {
	switch e {
	case Inbound:
		return true
	case Outbound:
		return true
	default:
		return false
	}
}

// Agent Control-plane snapshot of one enrolled agent. Mirrors the Go
// `server.Agent` struct (`internal/controlplane/server/types.go`).
type Agent struct {
	// CertExpiresAt Expiry timestamp of the agent's current certificate.
	CertExpiresAt *time.Time `json:"cert_expires_at,omitempty"`

	// CertIssuedAt Issuance timestamp of the agent's current certificate.
	CertIssuedAt *time.Time `json:"cert_issued_at,omitempty"`

	// CertificateRecovery Optional snapshot of any active certificate-recovery grant
	// for the agent. Absent when no grant has been issued.
	CertificateRecovery *AgentCertificateRecoveryGrant `json:"certificate_recovery,omitempty"`

	// FleetGroupId UUID of the fleet group the agent belongs to.
	FleetGroupId string `json:"fleet_group_id"`

	// Id Agent UUID.
	Id string `json:"id"`

	// LastSeenAt Last successful heartbeat timestamp.
	LastSeenAt time.Time `json:"last_seen_at"`

	// NodeName Operator-facing display name.
	NodeName string `json:"node_name"`

	// PresenceState Live presence evaluation — `online`, `flapping`, `offline`, etc.
	// Computed at request time from session + heartbeat data.
	PresenceState string `json:"presence_state"`

	// ReadOnly True when the agent serves read-only Telemt instances.
	ReadOnly bool `json:"read_only"`

	// Runtime Telemt operator overview reported by the agent. The set of
	// fields is defensive on the Zod side because backends can ship
	// new counters without an immediate web release; on the spec
	// side we list every field the panel currently consumes.
	Runtime AgentRuntime `json:"runtime"`

	// Version Agent binary semver as last reported.
	Version string `json:"version"`
}

// AgentCertificateRecoveryGrant Lifecycle snapshot of a single recovery grant.
type AgentCertificateRecoveryGrant struct {
	AgentId       string                              `json:"agent_id"`
	ExpiresAtUnix int64                               `json:"expires_at_unix"`
	IssuedAtUnix  int64                               `json:"issued_at_unix"`
	RevokedAtUnix *int64                              `json:"revoked_at_unix,omitempty"`
	Status        AgentCertificateRecoveryGrantStatus `json:"status"`
	UsedAtUnix    *int64                              `json:"used_at_unix,omitempty"`
}

// AgentCertificateRecoveryGrantStatus defines model for AgentCertificateRecoveryGrant.Status.
type AgentCertificateRecoveryGrantStatus string

// AgentList List response from `GET /api/agents`.
type AgentList = []Agent

// AgentRuntime Telemt operator overview reported by the agent. The set of
// fields is defensive on the Zod side because backends can ship
// new counters without an immediate web release; on the spec
// side we list every field the panel currently consumes.
type AgentRuntime struct {
	AcceptingNewConnections  bool        `json:"accepting_new_connections"`
	ActiveUsers              int         `json:"active_users"`
	ConfiguredUsers          int         `json:"configured_users"`
	ConnectAttemptTotal      int64       `json:"connect_attempt_total"`
	ConnectFailTotal         int64       `json:"connect_fail_total"`
	ConnectFailfastTotal     int64       `json:"connect_failfast_total"`
	ConnectSuccessTotal      int64       `json:"connect_success_total"`
	ConnectionsBadTotal      int64       `json:"connections_bad_total"`
	ConnectionsTotal         int64       `json:"connections_total"`
	CurrentConnections       int         `json:"current_connections"`
	CurrentConnectionsDirect int         `json:"current_connections_direct"`
	CurrentConnectionsMe     int         `json:"current_connections_me"`
	DcCoveragePct            float64     `json:"dc_coverage_pct"`
	Dcs                      []RuntimeDC `json:"dcs"`
	Degraded                 bool        `json:"degraded"`
	FailRateKnown            bool        `json:"fail_rate_known"`

	// FailRatePct5m 5-minute upstream connect fail-rate. Read together with
	// `fail_rate_known`: `false` means "unknown", not "0%".
	FailRatePct5m float64 `json:"fail_rate_pct_5m"`

	// FallbackEnteredAtUnix Unix timestamp the panel observed this agent enter
	// ME→DC fallback. Absent when not in fallback.
	FallbackEnteredAtUnix      *int64                     `json:"fallback_entered_at_unix,omitempty"`
	HandshakeTimeoutsTotal     int64                      `json:"handshake_timeouts_total"`
	HealthyUpstreams           int                        `json:"healthy_upstreams"`
	InitializationProgressPct  float64                    `json:"initialization_progress_pct"`
	InitializationStage        string                     `json:"initialization_stage"`
	InitializationStatus       string                     `json:"initialization_status"`
	LifecycleState             *string                    `json:"lifecycle_state,omitempty"`
	Me2dcFallbackEnabled       bool                       `json:"me2dc_fallback_enabled"`
	Me2dcFastEnabled           *bool                      `json:"me2dc_fast_enabled,omitempty"`
	MeRuntimeReady             bool                       `json:"me_runtime_ready"`
	MeWritersSummary           *RuntimeMeWritersSummary   `json:"me_writers_summary,omitempty"`
	RecentEvents               []RuntimeEvent             `json:"recent_events"`
	RerouteActive              *bool                      `json:"reroute_active,omitempty"`
	RouteMode                  *string                    `json:"route_mode,omitempty"`
	StaleCacheUsed             *bool                      `json:"stale_cache_used,omitempty"`
	StartupProgressPct         float64                    `json:"startup_progress_pct"`
	StartupStage               string                     `json:"startup_stage"`
	StartupStatus              string                     `json:"startup_status"`
	SystemLoad                 RuntimeSystemLoad          `json:"system_load"`
	TelemtUnreachable          bool                       `json:"telemt_unreachable"`
	TelemtUnreachableSinceUnix int64                      `json:"telemt_unreachable_since_unix"`
	TopByConnections           *[]RuntimeTopByConnections `json:"top_by_connections,omitempty"`
	TopByThroughput            *[]RuntimeTopByThroughput  `json:"top_by_throughput,omitempty"`
	TotalUpstreams             int                        `json:"total_upstreams"`
	TransportMode              string                     `json:"transport_mode"`
	UpdatedAt                  time.Time                  `json:"updated_at"`
	Upstreams                  []RuntimeUpstream          `json:"upstreams"`
	UptimeSeconds              float64                    `json:"uptime_seconds"`
	UseMiddleProxy             bool                       `json:"use_middle_proxy"`
}

// CreateCertificateRecoveryGrantRequest defines model for CreateCertificateRecoveryGrantRequest.
type CreateCertificateRecoveryGrantRequest struct {
	// TtlSeconds Grant lifetime in seconds. Zero or omitted yields the
	// server's default TTL (15m, capped at 1h).
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// CreateEnrollmentTokenRequest defines model for CreateEnrollmentTokenRequest.
type CreateEnrollmentTokenRequest struct {
	// FleetGroupId Either the canonical UUID or the friendly slug; empty
	// string falls back to the default fleet group.
	FleetGroupId *string `json:"fleet_group_id,omitempty"`

	// TtlSeconds Token lifetime in seconds.
	TtlSeconds int `json:"ttl_seconds"`
}

// CreateEnrollmentTokenResponse Response to a successful `POST /api/agents/enrollment-tokens`.
// The raw `value` is exposed once at this moment; subsequent
// listings only carry the masked form.
type CreateEnrollmentTokenResponse struct {
	// CaPem PEM-encoded panel CA certificate.
	CaPem         string `json:"ca_pem"`
	ExpiresAtUnix int64  `json:"expires_at_unix"`
	FleetGroupId  string `json:"fleet_group_id"`
	IssuedAtUnix  int64  `json:"issued_at_unix"`
	PanelUrl      string `json:"panel_url"`

	// Value The raw bootstrap token. Returned only at creation.
	Value string `json:"value"`
}

// DispatchAgentUpdateRequest defines model for DispatchAgentUpdateRequest.
type DispatchAgentUpdateRequest struct {
	// Version Target agent binary version.
	Version string `json:"version"`
}

// DispatchAgentUpdateResponse defines model for DispatchAgentUpdateResponse.
type DispatchAgentUpdateResponse struct {
	JobId   string `json:"job_id"`
	Status  string `json:"status"`
	Version string `json:"version"`
}

// EnrollmentTokenList defines model for EnrollmentTokenList.
type EnrollmentTokenList = []EnrollmentTokenListItem

// EnrollmentTokenListItem Listing-safe view of an enrollment token. The raw `value` is
// intentionally absent — only the creation response surfaces
// the bearer secret. Use `handle` (SHA-256 prefix) to revoke.
type EnrollmentTokenListItem struct {
	ConsumedAtUnix *int64 `json:"consumed_at_unix,omitempty"`
	ExpiresAtUnix  int64  `json:"expires_at_unix"`
	FleetGroupId   string `json:"fleet_group_id"`

	// Handle SHA-256 prefix of the raw value, hex-encoded.
	Handle       *string `json:"handle,omitempty"`
	IssuedAtUnix int64   `json:"issued_at_unix"`

	// MaskedValue Truncated form of the raw value, ellipsis-suffixed.
	MaskedValue   *string                       `json:"masked_value,omitempty"`
	PanelUrl      string                        `json:"panel_url"`
	RevokedAtUnix *int64                        `json:"revoked_at_unix,omitempty"`
	Status        EnrollmentTokenListItemStatus `json:"status"`
}

// EnrollmentTokenListItemStatus defines model for EnrollmentTokenListItem.Status.
type EnrollmentTokenListItemStatus string

// Error Standard error envelope used by every 4xx / 5xx response.
type Error struct {
	// Details Optional structured context. Shape varies per error code.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Machine-readable error code (e.g. `not_found`, `forbidden`).
	Error string `json:"error"`

	// Message Human-readable message; safe to display to operators.
	Message *string `json:"message,omitempty"`
}

// InstallCommandResponse Pre-baked `curl ... | sudo bash -s -- ...` one-liner the
// operator runs on the host to install or re-bootstrap a
// reverse-mode agent.
type InstallCommandResponse struct {
	Command       string `json:"command"`
	ExpiresAtUnix int64  `json:"expires_at_unix"`
}

// RenameAgentRequest defines model for RenameAgentRequest.
type RenameAgentRequest struct {
	NodeName string `json:"node_name"`
}

// RuntimeDC defines model for RuntimeDC.
type RuntimeDC struct {
	AliveWriters       int     `json:"alive_writers"`
	AvailableEndpoints int     `json:"available_endpoints"`
	AvailablePct       float64 `json:"available_pct"`
	CoveragePct        float64 `json:"coverage_pct"`
	Dc                 int     `json:"dc"`
	FreshAliveWriters  int     `json:"fresh_alive_writers"`
	FreshCoveragePct   float64 `json:"fresh_coverage_pct"`
	Load               int     `json:"load"`
	RequiredWriters    int     `json:"required_writers"`
	RttMs              float64 `json:"rtt_ms"`
}

// RuntimeEvent defines model for RuntimeEvent.
type RuntimeEvent struct {
	Context       string `json:"context"`
	EventType     string `json:"event_type"`
	Sequence      int64  `json:"sequence"`
	TimestampUnix int64  `json:"timestamp_unix"`
}

// RuntimeMeWritersSummary defines model for RuntimeMeWritersSummary.
type RuntimeMeWritersSummary struct {
	AliveWriters        int     `json:"alive_writers"`
	AvailableEndpoints  int     `json:"available_endpoints"`
	ConfiguredEndpoints int     `json:"configured_endpoints"`
	CoveragePct         float64 `json:"coverage_pct"`
	FreshAliveWriters   int     `json:"fresh_alive_writers"`
	FreshCoveragePct    float64 `json:"fresh_coverage_pct"`
	RequiredWriters     int     `json:"required_writers"`
}

// RuntimeSystemLoad defines model for RuntimeSystemLoad.
type RuntimeSystemLoad struct {
	CpuUsagePct      float64 `json:"cpu_usage_pct"`
	DiskTotalBytes   int64   `json:"disk_total_bytes"`
	DiskUsagePct     float64 `json:"disk_usage_pct"`
	DiskUsedBytes    int64   `json:"disk_used_bytes"`
	Load15m          float64 `json:"load_15m"`
	Load1m           float64 `json:"load_1m"`
	Load5m           float64 `json:"load_5m"`
	MemoryTotalBytes int64   `json:"memory_total_bytes"`
	MemoryUsagePct   float64 `json:"memory_usage_pct"`
	MemoryUsedBytes  int64   `json:"memory_used_bytes"`
	NetBytesRecv     int64   `json:"net_bytes_recv"`
	NetBytesSent     int64   `json:"net_bytes_sent"`
}

// RuntimeTopByConnections defines model for RuntimeTopByConnections.
type RuntimeTopByConnections struct {
	Connections int    `json:"connections"`
	Username    string `json:"username"`
}

// RuntimeTopByThroughput defines model for RuntimeTopByThroughput.
type RuntimeTopByThroughput struct {
	ThroughputBytes int64  `json:"throughput_bytes"`
	Username        string `json:"username"`
}

// RuntimeUpstream defines model for RuntimeUpstream.
type RuntimeUpstream struct {
	Address            string    `json:"address"`
	EffectiveLatencyMs float64   `json:"effective_latency_ms"`
	Fails              int       `json:"fails"`
	Healthy            bool      `json:"healthy"`
	LastCheckAgeSecs   int       `json:"last_check_age_secs"`
	RouteKind          string    `json:"route_kind"`
	Scopes             *[]string `json:"scopes,omitempty"`
	UpstreamId         int       `json:"upstream_id"`
	Weight             int       `json:"weight"`
}

// UpdateAgentFleetGroupRequest defines model for UpdateAgentFleetGroupRequest.
type UpdateAgentFleetGroupRequest struct {
	// FleetGroupId Target fleet-group UUID. Must already exist.
	FleetGroupId string `json:"fleet_group_id"`
}

// UpdateAgentTransportModeRequest defines model for UpdateAgentTransportModeRequest.
type UpdateAgentTransportModeRequest struct {
	// DialAddress Public host:port the panel dials (required for outbound).
	DialAddress *string `json:"dial_address,omitempty"`

	// ListenAddress Agent-side bind spec. Optional — defaults to `:<port>`
	// derived from `dial_address` when omitted.
	ListenAddress *string                                      `json:"listen_address,omitempty"`
	TransportMode UpdateAgentTransportModeRequestTransportMode `json:"transport_mode"`
}

// UpdateAgentTransportModeRequestTransportMode defines model for UpdateAgentTransportModeRequest.TransportMode.
type UpdateAgentTransportModeRequestTransportMode string

// VersionResponse Build metadata for the running control-plane process.
type VersionResponse struct {
	// BuildTime RFC3339 build timestamp. Operator+ only.
	BuildTime *time.Time `json:"build_time,omitempty"`

	// CommitSha Git commit hash baked in at build time. Operator+ only.
	CommitSha *string `json:"commit_sha,omitempty"`

	// Version Semantic version (or "dev" for unstamped builds).
	Version string `json:"version"`
}

// BadRequest Standard error envelope used by every 4xx / 5xx response.
type BadRequest = Error

// Forbidden Standard error envelope used by every 4xx / 5xx response.
type Forbidden = Error

// NotFound Standard error envelope used by every 4xx / 5xx response.
type NotFound = Error

// Unauthorized Standard error envelope used by every 4xx / 5xx response.
type Unauthorized = Error

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// CreateEnrollmentTokenJSONRequestBody defines body for CreateEnrollmentToken for application/json ContentType.
type CreateEnrollmentTokenJSONRequestBody = CreateEnrollmentTokenRequest

// RenameAgentJSONRequestBody defines body for RenameAgent for application/json ContentType.
type RenameAgentJSONRequestBody = RenameAgentRequest

// CreateAgentCertificateRecoveryGrantJSONRequestBody defines body for CreateAgentCertificateRecoveryGrant for application/json ContentType.
type CreateAgentCertificateRecoveryGrantJSONRequestBody = CreateCertificateRecoveryGrantRequest

// UpdateAgentFleetGroupJSONRequestBody defines body for UpdateAgentFleetGroup for application/json ContentType.
type UpdateAgentFleetGroupJSONRequestBody = UpdateAgentFleetGroupRequest

// UpdateAgentTransportModeJSONRequestBody defines body for UpdateAgentTransportMode for application/json ContentType.
type UpdateAgentTransportModeJSONRequestBody = UpdateAgentTransportModeRequest

// DispatchAgentUpdateJSONRequestBody defines body for DispatchAgentUpdate for application/json ContentType.
type DispatchAgentUpdateJSONRequestBody = DispatchAgentUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List enrolled agents in operator's fleet scope
	// (GET /api/agents)
	ListAgents(w http.ResponseWriter, r *http.Request)
	// List enrollment tokens visible to the operator
	// (GET /api/agents/enrollment-tokens)
	ListEnrollmentTokens(w http.ResponseWriter, r *http.Request)
	// Mint a new enrollment token
	// (POST /api/agents/enrollment-tokens)
	CreateEnrollmentToken(w http.ResponseWriter, r *http.Request)
	// Revoke an enrollment token
	// (POST /api/agents/enrollment-tokens/{value}/revoke)
	RevokeEnrollmentToken(w http.ResponseWriter, r *http.Request, value string)
	// Deregister an agent
	// (DELETE /api/agents/{id})
	DeregisterAgent(w http.ResponseWriter, r *http.Request, id string)
	// Rename an agent's display node-name
	// (PATCH /api/agents/{id})
	RenameAgent(w http.ResponseWriter, r *http.Request, id string)
	// Allow an agent to recover an expired certificate
	// (POST /api/agents/{id}/certificate-recovery-grants)
	CreateAgentCertificateRecoveryGrant(w http.ResponseWriter, r *http.Request, id string)
	// Revoke a previously-issued recovery grant
	// (POST /api/agents/{id}/certificate-recovery-grants/revoke)
	RevokeAgentCertificateRecoveryGrant(w http.ResponseWriter, r *http.Request, id string)
	// Reassign an agent to a different fleet group
	// (PUT /api/agents/{id}/fleet-group)
	UpdateAgentFleetGroup(w http.ResponseWriter, r *http.Request, id string)
	// Generate a one-line installer for an outbound agent
	// (POST /api/agents/{id}/install-command)
	CreateAgentInstallCommand(w http.ResponseWriter, r *http.Request, id string)
	// Switch an agent between inbound and outbound transport
	// (PUT /api/agents/{id}/transport-mode)
	UpdateAgentTransportMode(w http.ResponseWriter, r *http.Request, id string)
	// Enqueue a self-update job for an agent
	// (POST /api/agents/{id}/update)
	DispatchAgentUpdate(w http.ResponseWriter, r *http.Request, id string)
	// Panel build identification
	// (GET /api/version)
	GetVersion(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List enrolled agents in operator's fleet scope
// (GET /api/agents)
func (_ Unimplemented) ListAgents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List enrollment tokens visible to the operator
// (GET /api/agents/enrollment-tokens)
func (_ Unimplemented) ListEnrollmentTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mint a new enrollment token
// (POST /api/agents/enrollment-tokens)
func (_ Unimplemented) CreateEnrollmentToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke an enrollment token
// (POST /api/agents/enrollment-tokens/{value}/revoke)
func (_ Unimplemented) RevokeEnrollmentToken(w http.ResponseWriter, r *http.Request, value string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deregister an agent
// (DELETE /api/agents/{id})
func (_ Unimplemented) DeregisterAgent(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename an agent's display node-name
// (PATCH /api/agents/{id})
func (_ Unimplemented) RenameAgent(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Allow an agent to recover an expired certificate
// (POST /api/agents/{id}/certificate-recovery-grants)
func (_ Unimplemented) CreateAgentCertificateRecoveryGrant(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a previously-issued recovery grant
// (POST /api/agents/{id}/certificate-recovery-grants/revoke)
func (_ Unimplemented) RevokeAgentCertificateRecoveryGrant(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reassign an agent to a different fleet group
// (PUT /api/agents/{id}/fleet-group)
func (_ Unimplemented) UpdateAgentFleetGroup(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a one-line installer for an outbound agent
// (POST /api/agents/{id}/install-command)
func (_ Unimplemented) CreateAgentInstallCommand(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Switch an agent between inbound and outbound transport
// (PUT /api/agents/{id}/transport-mode)
func (_ Unimplemented) UpdateAgentTransportMode(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Enqueue a self-update job for an agent
// (POST /api/agents/{id}/update)
func (_ Unimplemented) DispatchAgentUpdate(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Panel build identification
// (GET /api/version)
func (_ Unimplemented) GetVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEnrollmentTokens operation middleware
func (siw *ServerInterfaceWrapper) ListEnrollmentTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEnrollmentTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEnrollmentToken operation middleware
func (siw *ServerInterfaceWrapper) CreateEnrollmentToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEnrollmentToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeEnrollmentToken operation middleware
func (siw *ServerInterfaceWrapper) RevokeEnrollmentToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "value" -------------
	var value string

	err = runtime.BindStyledParameterWithOptions("simple", "value", chi.URLParam(r, "value"), &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "value", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeEnrollmentToken(w, r, value)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeregisterAgent operation middleware
func (siw *ServerInterfaceWrapper) DeregisterAgent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeregisterAgent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameAgent operation middleware
func (siw *ServerInterfaceWrapper) RenameAgent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameAgent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgentCertificateRecoveryGrant operation middleware
func (siw *ServerInterfaceWrapper) CreateAgentCertificateRecoveryGrant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgentCertificateRecoveryGrant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeAgentCertificateRecoveryGrant operation middleware
func (siw *ServerInterfaceWrapper) RevokeAgentCertificateRecoveryGrant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeAgentCertificateRecoveryGrant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAgentFleetGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateAgentFleetGroup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAgentFleetGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgentInstallCommand operation middleware
func (siw *ServerInterfaceWrapper) CreateAgentInstallCommand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgentInstallCommand(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAgentTransportMode operation middleware
func (siw *ServerInterfaceWrapper) UpdateAgentTransportMode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAgentTransportMode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DispatchAgentUpdate operation middleware
func (siw *ServerInterfaceWrapper) DispatchAgentUpdate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DispatchAgentUpdate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/agents", wrapper.ListAgents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/agents/enrollment-tokens", wrapper.ListEnrollmentTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/agents/enrollment-tokens", wrapper.CreateEnrollmentToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/agents/enrollment-tokens/{value}/revoke", wrapper.RevokeEnrollmentToken)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/agents/{id}", wrapper.DeregisterAgent)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/agents/{id}", wrapper.RenameAgent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/agents/{id}/certificate-recovery-grants", wrapper.CreateAgentCertificateRecoveryGrant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/agents/{id}/certificate-recovery-grants/revoke", wrapper.RevokeAgentCertificateRecoveryGrant)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/agents/{id}/fleet-group", wrapper.UpdateAgentFleetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/agents/{id}/install-command", wrapper.CreateAgentInstallCommand)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/agents/{id}/transport-mode", wrapper.UpdateAgentTransportMode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/agents/{id}/update", wrapper.DispatchAgentUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/version", wrapper.GetVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})

	return r
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListAgentsRequestObject struct {
}

type ListAgentsResponseObject interface {
	VisitListAgentsResponse(w http.ResponseWriter) error
}

type ListAgents200JSONResponse AgentList

func (response ListAgents200JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgents401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAgents401JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgents403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListAgents403JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListEnrollmentTokensRequestObject struct {
}

type ListEnrollmentTokensResponseObject interface {
	VisitListEnrollmentTokensResponse(w http.ResponseWriter) error
}

type ListEnrollmentTokens200JSONResponse EnrollmentTokenList

func (response ListEnrollmentTokens200JSONResponse) VisitListEnrollmentTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEnrollmentTokens401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListEnrollmentTokens401JSONResponse) VisitListEnrollmentTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListEnrollmentTokens403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListEnrollmentTokens403JSONResponse) VisitListEnrollmentTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEnrollmentTokenRequestObject struct {
	Body *CreateEnrollmentTokenJSONRequestBody
}

type CreateEnrollmentTokenResponseObject interface {
	VisitCreateEnrollmentTokenResponse(w http.ResponseWriter) error
}

type CreateEnrollmentToken201JSONResponse CreateEnrollmentTokenResponse

func (response CreateEnrollmentToken201JSONResponse) VisitCreateEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEnrollmentToken400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateEnrollmentToken400JSONResponse) VisitCreateEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEnrollmentToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateEnrollmentToken401JSONResponse) VisitCreateEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEnrollmentToken403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateEnrollmentToken403JSONResponse) VisitCreateEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeEnrollmentTokenRequestObject struct {
	Value string `json:"value"`
}

type RevokeEnrollmentTokenResponseObject interface {
	VisitRevokeEnrollmentTokenResponse(w http.ResponseWriter) error
}

type RevokeEnrollmentToken204Response struct {
}

func (response RevokeEnrollmentToken204Response) VisitRevokeEnrollmentTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeEnrollmentToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeEnrollmentToken401JSONResponse) VisitRevokeEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeEnrollmentToken403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeEnrollmentToken403JSONResponse) VisitRevokeEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeEnrollmentToken404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeEnrollmentToken404JSONResponse) VisitRevokeEnrollmentTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeregisterAgentRequestObject struct {
	Id string `json:"id"`
}

type DeregisterAgentResponseObject interface {
	VisitDeregisterAgentResponse(w http.ResponseWriter) error
}

type DeregisterAgent204Response struct {
}

func (response DeregisterAgent204Response) VisitDeregisterAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeregisterAgent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeregisterAgent401JSONResponse) VisitDeregisterAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeregisterAgent403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeregisterAgent403JSONResponse) VisitDeregisterAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeregisterAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response DeregisterAgent404JSONResponse) VisitDeregisterAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RenameAgentRequestObject struct {
	Id   string `json:"id"`
	Body *RenameAgentJSONRequestBody
}

type RenameAgentResponseObject interface {
	VisitRenameAgentResponse(w http.ResponseWriter) error
}

type RenameAgent200JSONResponse Agent

func (response RenameAgent200JSONResponse) VisitRenameAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RenameAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response RenameAgent400JSONResponse) VisitRenameAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RenameAgent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RenameAgent401JSONResponse) VisitRenameAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RenameAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response RenameAgent404JSONResponse) VisitRenameAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentCertificateRecoveryGrantRequestObject struct {
	Id   string `json:"id"`
	Body *CreateAgentCertificateRecoveryGrantJSONRequestBody
}

type CreateAgentCertificateRecoveryGrantResponseObject interface {
	VisitCreateAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error
}

type CreateAgentCertificateRecoveryGrant201JSONResponse AgentCertificateRecoveryGrant

func (response CreateAgentCertificateRecoveryGrant201JSONResponse) VisitCreateAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentCertificateRecoveryGrant400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAgentCertificateRecoveryGrant400JSONResponse) VisitCreateAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentCertificateRecoveryGrant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAgentCertificateRecoveryGrant401JSONResponse) VisitCreateAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentCertificateRecoveryGrant403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateAgentCertificateRecoveryGrant403JSONResponse) VisitCreateAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentCertificateRecoveryGrant404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateAgentCertificateRecoveryGrant404JSONResponse) VisitCreateAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAgentCertificateRecoveryGrantRequestObject struct {
	Id string `json:"id"`
}

type RevokeAgentCertificateRecoveryGrantResponseObject interface {
	VisitRevokeAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error
}

type RevokeAgentCertificateRecoveryGrant200JSONResponse AgentCertificateRecoveryGrant

func (response RevokeAgentCertificateRecoveryGrant200JSONResponse) VisitRevokeAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAgentCertificateRecoveryGrant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeAgentCertificateRecoveryGrant401JSONResponse) VisitRevokeAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAgentCertificateRecoveryGrant403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeAgentCertificateRecoveryGrant403JSONResponse) VisitRevokeAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAgentCertificateRecoveryGrant404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeAgentCertificateRecoveryGrant404JSONResponse) VisitRevokeAgentCertificateRecoveryGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAgentFleetGroupRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateAgentFleetGroupJSONRequestBody
}

type UpdateAgentFleetGroupResponseObject interface {
	VisitUpdateAgentFleetGroupResponse(w http.ResponseWriter) error
}

type UpdateAgentFleetGroup200JSONResponse Agent

func (response UpdateAgentFleetGroup200JSONResponse) VisitUpdateAgentFleetGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAgentFleetGroup400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateAgentFleetGroup400JSONResponse) VisitUpdateAgentFleetGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAgentFleetGroup401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateAgentFleetGroup401JSONResponse) VisitUpdateAgentFleetGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAgentFleetGroup403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateAgentFleetGroup403JSONResponse) VisitUpdateAgentFleetGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAgentFleetGroup404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateAgentFleetGroup404JSONResponse) VisitUpdateAgentFleetGroupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentInstallCommandRequestObject struct {
	Id string `json:"id"`
}

type CreateAgentInstallCommandResponseObject interface {
	VisitCreateAgentInstallCommandResponse(w http.ResponseWriter) error
}

type CreateAgentInstallCommand200JSONResponse InstallCommandResponse

func (response CreateAgentInstallCommand200JSONResponse) VisitCreateAgentInstallCommandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentInstallCommand400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAgentInstallCommand400JSONResponse) VisitCreateAgentInstallCommandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentInstallCommand401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAgentInstallCommand401JSONResponse) VisitCreateAgentInstallCommandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentInstallCommand404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateAgentInstallCommand404JSONResponse) VisitCreateAgentInstallCommandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentInstallCommand503TextResponse string

func (response CreateAgentInstallCommand503TextResponse) VisitCreateAgentInstallCommandResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(503)

	_, err := w.Write([]byte(response))
	return err
}

type UpdateAgentTransportModeRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateAgentTransportModeJSONRequestBody
}

type UpdateAgentTransportModeResponseObject interface {
	VisitUpdateAgentTransportModeResponse(w http.ResponseWriter) error
}

type UpdateAgentTransportMode204Response struct {
}

func (response UpdateAgentTransportMode204Response) VisitUpdateAgentTransportModeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateAgentTransportMode400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateAgentTransportMode400JSONResponse) VisitUpdateAgentTransportModeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAgentTransportMode401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateAgentTransportMode401JSONResponse) VisitUpdateAgentTransportModeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAgentTransportMode404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateAgentTransportMode404JSONResponse) VisitUpdateAgentTransportModeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DispatchAgentUpdateRequestObject struct {
	Id   string `json:"id"`
	Body *DispatchAgentUpdateJSONRequestBody
}

type DispatchAgentUpdateResponseObject interface {
	VisitDispatchAgentUpdateResponse(w http.ResponseWriter) error
}

type DispatchAgentUpdate200JSONResponse DispatchAgentUpdateResponse

func (response DispatchAgentUpdate200JSONResponse) VisitDispatchAgentUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DispatchAgentUpdate400JSONResponse struct{ BadRequestJSONResponse }

func (response DispatchAgentUpdate400JSONResponse) VisitDispatchAgentUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DispatchAgentUpdate401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DispatchAgentUpdate401JSONResponse) VisitDispatchAgentUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DispatchAgentUpdate404JSONResponse struct{ NotFoundJSONResponse }

func (response DispatchAgentUpdate404JSONResponse) VisitDispatchAgentUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse VersionResponse

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersion401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetVersion401JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200TextResponse string

func (response GetHealthz200TextResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List enrolled agents in operator's fleet scope
	// (GET /api/agents)
	ListAgents(ctx context.Context, request ListAgentsRequestObject) (ListAgentsResponseObject, error)
	// List enrollment tokens visible to the operator
	// (GET /api/agents/enrollment-tokens)
	ListEnrollmentTokens(ctx context.Context, request ListEnrollmentTokensRequestObject) (ListEnrollmentTokensResponseObject, error)
	// Mint a new enrollment token
	// (POST /api/agents/enrollment-tokens)
	CreateEnrollmentToken(ctx context.Context, request CreateEnrollmentTokenRequestObject) (CreateEnrollmentTokenResponseObject, error)
	// Revoke an enrollment token
	// (POST /api/agents/enrollment-tokens/{value}/revoke)
	RevokeEnrollmentToken(ctx context.Context, request RevokeEnrollmentTokenRequestObject) (RevokeEnrollmentTokenResponseObject, error)
	// Deregister an agent
	// (DELETE /api/agents/{id})
	DeregisterAgent(ctx context.Context, request DeregisterAgentRequestObject) (DeregisterAgentResponseObject, error)
	// Rename an agent's display node-name
	// (PATCH /api/agents/{id})
	RenameAgent(ctx context.Context, request RenameAgentRequestObject) (RenameAgentResponseObject, error)
	// Allow an agent to recover an expired certificate
	// (POST /api/agents/{id}/certificate-recovery-grants)
	CreateAgentCertificateRecoveryGrant(ctx context.Context, request CreateAgentCertificateRecoveryGrantRequestObject) (CreateAgentCertificateRecoveryGrantResponseObject, error)
	// Revoke a previously-issued recovery grant
	// (POST /api/agents/{id}/certificate-recovery-grants/revoke)
	RevokeAgentCertificateRecoveryGrant(ctx context.Context, request RevokeAgentCertificateRecoveryGrantRequestObject) (RevokeAgentCertificateRecoveryGrantResponseObject, error)
	// Reassign an agent to a different fleet group
	// (PUT /api/agents/{id}/fleet-group)
	UpdateAgentFleetGroup(ctx context.Context, request UpdateAgentFleetGroupRequestObject) (UpdateAgentFleetGroupResponseObject, error)
	// Generate a one-line installer for an outbound agent
	// (POST /api/agents/{id}/install-command)
	CreateAgentInstallCommand(ctx context.Context, request CreateAgentInstallCommandRequestObject) (CreateAgentInstallCommandResponseObject, error)
	// Switch an agent between inbound and outbound transport
	// (PUT /api/agents/{id}/transport-mode)
	UpdateAgentTransportMode(ctx context.Context, request UpdateAgentTransportModeRequestObject) (UpdateAgentTransportModeResponseObject, error)
	// Enqueue a self-update job for an agent
	// (POST /api/agents/{id}/update)
	DispatchAgentUpdate(ctx context.Context, request DispatchAgentUpdateRequestObject) (DispatchAgentUpdateResponseObject, error)
	// Panel build identification
	// (GET /api/version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAgents operation middleware
func (sh *strictHandler) ListAgents(w http.ResponseWriter, r *http.Request) {
	var request ListAgentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAgents(ctx, request.(ListAgentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAgents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAgentsResponseObject); ok {
		if err := validResponse.VisitListAgentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEnrollmentTokens operation middleware
func (sh *strictHandler) ListEnrollmentTokens(w http.ResponseWriter, r *http.Request) {
	var request ListEnrollmentTokensRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEnrollmentTokens(ctx, request.(ListEnrollmentTokensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEnrollmentTokens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEnrollmentTokensResponseObject); ok {
		if err := validResponse.VisitListEnrollmentTokensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEnrollmentToken operation middleware
func (sh *strictHandler) CreateEnrollmentToken(w http.ResponseWriter, r *http.Request) {
	var request CreateEnrollmentTokenRequestObject

	var body CreateEnrollmentTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEnrollmentToken(ctx, request.(CreateEnrollmentTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEnrollmentToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEnrollmentTokenResponseObject); ok {
		if err := validResponse.VisitCreateEnrollmentTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeEnrollmentToken operation middleware
func (sh *strictHandler) RevokeEnrollmentToken(w http.ResponseWriter, r *http.Request, value string) {
	var request RevokeEnrollmentTokenRequestObject

	request.Value = value

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeEnrollmentToken(ctx, request.(RevokeEnrollmentTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeEnrollmentToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeEnrollmentTokenResponseObject); ok {
		if err := validResponse.VisitRevokeEnrollmentTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeregisterAgent operation middleware
func (sh *strictHandler) DeregisterAgent(w http.ResponseWriter, r *http.Request, id string) {
	var request DeregisterAgentRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeregisterAgent(ctx, request.(DeregisterAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeregisterAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeregisterAgentResponseObject); ok {
		if err := validResponse.VisitDeregisterAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RenameAgent operation middleware
func (sh *strictHandler) RenameAgent(w http.ResponseWriter, r *http.Request, id string) {
	var request RenameAgentRequestObject

	request.Id = id

	var body RenameAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RenameAgent(ctx, request.(RenameAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RenameAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RenameAgentResponseObject); ok {
		if err := validResponse.VisitRenameAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAgentCertificateRecoveryGrant operation middleware
func (sh *strictHandler) CreateAgentCertificateRecoveryGrant(w http.ResponseWriter, r *http.Request, id string) {
	var request CreateAgentCertificateRecoveryGrantRequestObject

	request.Id = id

	var body CreateAgentCertificateRecoveryGrantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAgentCertificateRecoveryGrant(ctx, request.(CreateAgentCertificateRecoveryGrantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAgentCertificateRecoveryGrant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAgentCertificateRecoveryGrantResponseObject); ok {
		if err := validResponse.VisitCreateAgentCertificateRecoveryGrantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeAgentCertificateRecoveryGrant operation middleware
func (sh *strictHandler) RevokeAgentCertificateRecoveryGrant(w http.ResponseWriter, r *http.Request, id string) {
	var request RevokeAgentCertificateRecoveryGrantRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeAgentCertificateRecoveryGrant(ctx, request.(RevokeAgentCertificateRecoveryGrantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeAgentCertificateRecoveryGrant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeAgentCertificateRecoveryGrantResponseObject); ok {
		if err := validResponse.VisitRevokeAgentCertificateRecoveryGrantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAgentFleetGroup operation middleware
func (sh *strictHandler) UpdateAgentFleetGroup(w http.ResponseWriter, r *http.Request, id string) {
	var request UpdateAgentFleetGroupRequestObject

	request.Id = id

	var body UpdateAgentFleetGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAgentFleetGroup(ctx, request.(UpdateAgentFleetGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAgentFleetGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAgentFleetGroupResponseObject); ok {
		if err := validResponse.VisitUpdateAgentFleetGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAgentInstallCommand operation middleware
func (sh *strictHandler) CreateAgentInstallCommand(w http.ResponseWriter, r *http.Request, id string) {
	var request CreateAgentInstallCommandRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAgentInstallCommand(ctx, request.(CreateAgentInstallCommandRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAgentInstallCommand")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAgentInstallCommandResponseObject); ok {
		if err := validResponse.VisitCreateAgentInstallCommandResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAgentTransportMode operation middleware
func (sh *strictHandler) UpdateAgentTransportMode(w http.ResponseWriter, r *http.Request, id string) {
	var request UpdateAgentTransportModeRequestObject

	request.Id = id

	var body UpdateAgentTransportModeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAgentTransportMode(ctx, request.(UpdateAgentTransportModeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAgentTransportMode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAgentTransportModeResponseObject); ok {
		if err := validResponse.VisitUpdateAgentTransportModeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DispatchAgentUpdate operation middleware
func (sh *strictHandler) DispatchAgentUpdate(w http.ResponseWriter, r *http.Request, id string) {
	var request DispatchAgentUpdateRequestObject

	request.Id = id

	var body DispatchAgentUpdateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DispatchAgentUpdate(ctx, request.(DispatchAgentUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DispatchAgentUpdate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DispatchAgentUpdateResponseObject); ok {
		if err := validResponse.VisitDispatchAgentUpdateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3H3vchs3kvirdPH3u4pdISk5cfbq5NoPjuMkvrVjlyXv1W3GNQRnmhxEmMYEwFDi5lSVT/cAV3nCPMkV",
	"gPnLwZCUbHk39ykyB2g0Gt2N/ov8MklkXkhCMnpy9stEoS4kaXT/+Jqlb/HnErWx/0okGST3JysKwRNm",
	"uKSTn7Qk+5tOMsyZ/ev/K1xNzib/76QFfeK/6pPnSkk1ubm5mU5S1InihQUyOZv8lQmeOoiAdsx8cjOd",
	"fCvVkqcp0v2v/4wJgQq4BlaaDMlY+JjCsjQgWHKpwWQICn8uucIUlBR4ohNZoEP0B2m+lSWl949ndSAW",
	"BdSyVAlCKlEDSQN4zbUB6XYhSzOTq1mL4juyG5OK/x3TT0lOi1iPpPOJHV5BsAs8XVd47ICQZJQUs0Iw",
	"QtDECp1JA3IFkhCQlBQCU2B29hxecYuKP6XvZEQLjWqDau6AL0AbVSYGHiw4GVTExEniwTvoJ37widkW",
	"qOdruXg4j2gynRRKFqgM9+KQoDIxXhdcoY5ZAOPn9tsWDM9RG5YXFleLj0PxMw1JqRSSAQuIrxw15pPp",
	"ZCVVbsFNUmZwZmdPphOLyuRsoo3itLbn51bnWpeYBhd/oXXJKMF7XL6aFCtM5AbV1vGOEK9Xk7Mf9/OJ",
	"O4VnLYi3FYTvFCMzuXm/yz6v3R9M9I6d0RZYYvgGu1uY1djA2gKLaCVVu+05PF1qu+mrDAlI+kGQMQ1L",
	"RAJPUHvaN9PJSiCaeK1kWcQ8HZL43bsX39REdWPBjW1XgyUKSWsNRs5DRAwBdaQBCzo4RTBtYo1IwUN/",
	"ybQBXSYJar0qBWTIlFkiMy0XHH/EJFOMieU4XOd1gYoZqWYrlnBaQ8p1IdgW7Ogg2oVCjZRgrA0zAYAv",
	"7SnWgwA3TJRe+f/+62+wkCQ44WIKi5VgRcFpbf+Wq1X1M5pkHtEzmRel1YTMOMWM2m8bVkrmoFFrC/Dz",
	"DlFSZpiX7AHCClkaSxLbIa4XqkTPP+1BO4Whwc6a2VlwgQJzA5y0sVKoO1RZSimQOQ5TJTnqnx0hLm+r",
	"sTfTyQaV5l4vh5hnyYmpLWjMN6iAabBMAwoLqZy+HWzX7dffZJOzHy1bdk9/IAgtAl06DQ653d4O275v",
	"EJDLnzAxdkv7NUKAX1aYbBPRvwgYaE5rYe/lrg6YD1S3O7RKpgdH36r0uCR+bcc0AsPJ/OlxS0B7e6xR",
	"OVmuVfFtJincyMsDs6gUgi0FTs6MKjEExZK7dPtCKnN7gkwIeYX2pPxm7F+ldv+pluwcQrtzO+SDcNlh",
	"pIbMDY4DOg3JPcodL7kOcoLjbW+melFffPf8Ak5YwU8cAnphGYAbzPVRgmYXrDBgSrFtg8DbVlp3NIIX",
	"dllpRbC8t+F41cgcLLfdO+giQ9BoWTaiFUeRamsZpbhC0lYRSq9a/iZT0DxFWGLCSo2wZMklUqohYQQ6",
	"40VEhFeQyNJaMRquuMlkaYAR8DzHlDODcIVLUCiQaXxSQ9YFJhE52FcIwpIQnbw4bNyQghGK2kYQW0gk",
	"6TJHHbKEWJJgYTitY8KrOJFEmFjS6I58dbSev7TjUqPqjuhwdCJpxdelwvTAKLtQzIzBvDCxkYaJIN/m",
	"nHhuReN0ugfOinHxUYCsrLb7UEDVNf6hcOwxxEuWfhQ4d4bh2WiENfYPjFOurBo4eryX0OHYNIndrcDW",
	"GBceYGsIydKqtQZ3KvNlPcuhepT6qBTEN89CKiTFtWIppmGZcLynrDV9SfKKDg0qEhN/lQ810VeznFNp",
	"EMpCG4Ush4oyYOfO7Nw5vEWWgpFrNBkqpzQiWuwgsDiDxYoJjQvIkZGGaFKS+xJNps6Jiyan/xJNvDo4",
	"go4rJoTVXzFaXdW/Z3bMauLXHa+lVUZy6cwsq5+sX+5sHQctolfPf//v//nmGdSr7Nr51hJrP/ZxPv6i",
	"zRilOmOXGFv0ZGnuLhEZMmGybVyf04g8cOKGM8H/7qzhuFByraxSOJ5/dyBow9YYNHuGAyujYuiD1MZX",
	"a80PxuT4RZrEnUO3lB3h/XqsNofGxZVFGVuzczs66kpxex/Gusxz5v3SI8T2Ff6Hn3deTXPWTGLVC27q",
	"gNht9MDzzYg1oVDJ0mDsL8LwNvyIXKZh+mrDBMYJSzJ3kY5QTBumTFnchW/qqeMM0xkxxil6qw3msZAs",
	"PZJm527GSzvBEs4ZVnFJClmSeeEM7XM4LtbceiK3sMWNLOLldveKus15X8ji6+2zzvzA0VermEzJcp0V",
	"pbnTIhft9OAaholDmsUoRtpap+M8VhYpM0146bigQW/V2+zrXTUxtKGycEKvMZGU6iMZuNQY5zxNBVr2",
	"vw5qi11/ZdSODSifUR0XWHogLLvyNSKqY1q5Y02MaPj9V8fg+MMm2qh9tddQ2zHwB8cXMinHzNU9d27A",
	"SxjaeKGLdiggActqaJGN+RtjFnvQrxj1E7yh2ZWf3cunr02DuvGQIuyJdMjPfqaQGRwLw3SSP33/zxjR",
	"Fc6+OeemgrUZXDCOE1RD5/A3VBKsv5xzY73krfeFTYYR+RD8Z84tZqUwcHHxEh48+iqfQsKKwof5HmVV",
	"ZH6fsXUzutHnLmmQI5kLeYk0ur9DgeDn3FnS1lJNGEniCRPgo8P+15XiSKnYghbl+glY7tlG5LWmM0u1",
	"8+3BSDe83nInqDwSptxLebepIOW7FHt0MIzTXeT98cT0IZkhWvUXu1vWjVYv3rw+7wVuTrCBOTMWqF7M",
	"I7rIEBS7gsWGiRIXwDXgdSE1piApQcsXzkHIpZ34BHS51PZkyUQkuLb6XYML0iZMKR+YyZm+xBTstRJM",
	"9bC4wIC79eb5qxlSIlNMKx/l2dPdfMpHii8OeXBowd8lBOnQjkslgiAdiQOcVR3BUkqjjWIFuOOxrqUp",
	"FbmTEFt7EonlDS7pcNTZL9VFKBB4Phg9nNZnFWLUb7gumEkyF81751ThqMyPxtgvmFqjqRM8PtReDT5i",
	"kxXUo7FrhaiP3k9yOcYGnXDwNcsLazNP0gq2MxiGp9zudT/61aqdcO6+De1ohDp+e5RVGJj7wmDQOhwb",
	"GgwVc1rPNFshuPisyyJCq2VqNh6qmIi4y4+7NKRlbR9e+P3X3zyrO91f8XobjtalWrEEdUT2+xKZQmWV",
	"sEIzh3caYWHNG4ELeHD+/dPZF1/9CQqFK3790CpHH6oP6iMfjP3QxMG9aSK/q+EJ9DdZ504tpR2hp5Dh",
	"da1QwxnTu6g4r9zjMV2mSvK1HRZUACcUghea65kuVyt+PYLZfj16b4keH0Ho5nlq3tib69mR670698NS",
	"N74kZMgJhlHKVOqrewBpg0IWCKX22RKfjnh8fQ0n8NX1dSNSw1xeioZx4fMQacq9hL7pDPHUHCsocIUg",
	"1ocAVwFzbeZwnrECYcMURw0FqgpHy5Wdo2+3iOEtvmJJxgln1l2059oBAw9wvp7DgqSJV7Kk1OW26+qm",
	"xcMgh+WodRWL6S/0fZkzapepxj0Bp+eMbLLzRjYpKn34qvK7Ch3pC9KGCfFM5jmjdNzQe6NwtmTWrlok",
	"pRIwn8/hv0CXqYQl0xnMNMxm9tcFSMKZ4OSN6IiaTJoqSddJq0xqq6B9Tl0Ia1vbBRoThEWkLNtonFmf",
	"tkq2BbWnQ/yjJX93CFeDP04+3iKxHH1+ccwW6VVi5JxeIq1N1jXdR86wnRhcuklXDFZkwjrwVRw1HEBi",
	"G8advoqR0kLyKkC6b+Dx0cc7JWrCy68U6iw+YkN+4B1WrsObofy+P4v9Cytj4vy4sNbO+abJJHwQu1QP",
	"oDLdOeQdoocJF6RSs4OKFHt4zYfEB+xWqd6wRNopsf85ZO061y7BO+RgmhzTnUW9WXwArIf3tNngHtIM",
	"0g/3KpSd2NnBkbcWiPsXuWMEa6CWAzsek54PEIVDcraHBTrJj6GIFGVc6luqRK4vfXwxXm4N6jvIiANx",
	"p3VdMdFdl7V6JH7kM9xHauD40a1GHw07x1yq7QeSsQJyW0I20z6AlITGz40VJpsPAqAr5X0rALti2OPj",
	"0BaDJA+QcMhnAY4fcHDLLC0jdPhtsN0BAffI7yABGLro9hfAlBpVbentt+2akb3cyUH0LnqZx504fvPt",
	"ztx2J/wH6+7ZRJMnHF6PaapQhxPRuFqhT0oJZpCS7bEGl88DjRxWlVsK56RdyWuSYXIZW97TmIyZfy7T",
	"f8lHPBLXstFPpw7TAIOEqSdSPz7TWfMK+TozR9yaXUg9VKcNvVs61MQaoXezbJg4oUP3YVDnHX0rEM13",
	"SpbFnfM0VejWDZv5Wn1XaA+vSm2ACZfY9W0zVYrkaE9rZ+kDe7mos6+vZDoegk45E3GHq3e863IpeOK8",
	"4jMLqlMoZSdqeNB0J62kAlmapSwpfTiSSRJcG6Tx5RzeM1+Oyil1JaRzaOIov//6W5220tZJX5xF5enp",
	"l4nFzP2Fi4hSVHxj8XFVut3tLXyhVpUIHEt2DUoW6jAYJ7e3yXRSb/NwzGsHWujE/uqD2+MRjq9LLlLI",
	"0bCUGQZ1q4kqiTitIem1LBVKJqj1MIK1tFDicGnx22+fffnll/8GbkyniwPqFozPXfz5Fo07Ms+5iXXG",
	"AqlabsB/h4zpDHzwhhMw00EgtPa+lMJO4A9zRoYndc4EHkgF0STFTTRxBCzJ7dD12nGRahcMazMZj+aP",
	"5//6AXkW5zImpeJme55kmPsjqLpDnkl5yUNxa5eMnvkAaNNKkrjRrpJ7ue1mL4Vcc1rM4RVTl5hGdG4X",
	"RPgcvjemeE1iC5/DOcvxnBv880t2bUlcKJmW7g5/4nhoyRRGRJJmPliOqeuuAbaUGwSuq0TxpqlqdMQr",
	"BOM0+/7i4k1EQsrCfXjgNEMDH6o6Fou4hkUcfy+1mRWMNngdV3tbRMRJG2Spk2ztVi5NBishr6aQ8tUK",
	"ffOYpwEzRvFlaRzQSsVwSzn/3VpRziiY9Jdpz5EV/C+49a2DnFayjgowbytXs9+42ZAzToZxqspLlJic",
	"TTJjCn12crLmJiuX80TmJ8LuK5EpqhO/7ORmeqCRyVIOnr550YhytaLPxOeM2Bpzl0nuyfYcXvG1ckkE",
	"TolyQ1yayGm6jFE6q9oT/ybTiKok1xNfVC8MLK5weaJVcqIzpjB1TFRnwhYOl8Y5BZImoi1a0m/QavcM",
	"VZUkMtyIDpmqjkl449TP0zcvOvk6K0in81PLXJYqskBiBZ+cTb6cP5qfujSsyZxodPLx9p9rNKGUvikV",
	"6Spq71OjvhpCCEvWJp7rGhcQp7DiwpUBw3LrkmNc9a5lZ/TAg7ez89mjxw/n8JwlGSAZ5ZP2HD3/W8c6",
	"ooaf61ag9iasOp8SdPdOIUoNsrqyIuok6tuOIVfS6snpseaSXqRV9vDpuirF6fVFf3F6+tE6aNtOl0AX",
	"rW/v4rRBMlJtXR/v49NHYzAbJE96zb5u0peHJ7Xd1k5p1lEp33HT77fVVoPVh/yZrsTFHaJlS7bWTTuQ",
	"nry34PZWeRzJZ7t5W7jKpMY+H3Hj22I4+Rxs4hqRP9MDDnvLriooLu2ngammLOT3X3+L6Ig0L4SzvBE1",
	"ad4mq9v06rjSFSsjvazjGAPu5LrvlRVD6fsAU9ZVRtZm/kfzY8sLGjZc86XAuqaq5s4hP04n7eTJ+5vp",
	"pJB6pKHasoXLVTl9s1P94vQ0o1r9yQon4GSkZz57i6W9qq5ApQGouobm9Q8v/9Np9ydN4VLnHvA1T1Wh",
	"TbeACdjKoLpiKtUhNgpWa1WBS9Tma+kL6z8KC+0ts7vpG21GlXgzYOdH941LZdqPMraTdvdKgWXT08Ns",
	"2nkl4x8iDq84GWBAeDUQioO8f0gxn/zi2PTmxCsx57IyxXL0Mfgf9xRGqr5+rSsjtXE5a68fmyqYiOoy",
	"mEYYOFU3vpeDgm2FZOkcvpbWKpUq1+4FDGENgkrkndVaWIPHurbODpAq7Rin1sZpTdO6AK3PktMOe+36",
	"HO/HdIU1/P1t4LfMdKX2U9CyU5DYUSFVUbGOaMW4mMOLFPNCmrrIyE23G7cKxgcqZjVIv4anlI7oi9PH",
	"3U5QVqbctXfWyfC+OnjrgITUQU8OH4+Vl9ZIWDeujqBUvz38dBeCnfH48IzmXZa+yHgahErBbisxv/D0",
	"xlNKoAl2CqucEzOVrVA/xbF+++ZZ7VZOwU/WYG2Xln0j8vyr4UHzqsB0p9NdP5wCoxRYmnYWgBffNDLB",
	"aeYD6e6QvCL1DcBaAnPgfL+g5SArqjyNKL94eQ45M6g4E/6Kss60r8Gu4t0+NBBgsG9Q4dpuQfnu6mNY",
	"yxu6aTOz0b//9KzU7rYxBUIW8HS/3uw/AhLQVT4aeytFxUySBZotXVBS90yk2hkWbInCGRhPetzqKtsZ",
	"pX0PiqdIhputM5xLYi4CjGlPkz0g6fVRRE4htc9o2OvKxTfw55IJj48LxDr3kfBhWHc1tTP3ZMAEqnOO",
	"Mls+skMYMk/8yVUOWH23fVor5UM0rg9mUcNUzRMyMsVZnRc64DhabXsSevtn5rVhwD75OLIUvPSfpjkn",
	"7Z8QAub04czFojGtnhmyKrb2D7yvajVrX4wy5kx7F7dPGFWP4liLrlBSrmZyNSukru6KiKy2r+IbwMBV",
	"JHQbEBpDQOHM31uc1uNewf5XWO7TRzjUc/SJnYUDD1QNpdF3Of0RnIUPE9ynQsirnpdbyZyznmq+bQkX",
	"MqCa98JuLdDjfsc9ynVrzNe6qm907Vj3DFxvdv38WMKIpIElgsIUMbc3Yh3GsjCrjrxaQ1QhzHFL/bCI",
	"3udFdHuRqCjzR3MFrN7dcFlqsa3TPv1TvwNjdwKT98bBpRl/rQ3yUjtOdLHP1D1TBF+/vvjehzWr5wDt",
	"jWJcojwih6ueww9yJosm3qnhQWOa/fnP1eCHzu6r3fWInP/Qg+sfSnO19do7I4ngLofErBvp7i4/z3mu",
	"LsPMmZglzPUEKEZJFpKLYI3APV1We+sR/lksw6eVRci05muqfHOyR/jw//DN9Lbab+9yYp1UZSfueqxt",
	"WbUazDodA5/u3mkCzt6q2402P1BYCO+oMdpCobhU/tPD2iz0twwLt1/sNF003p/LpzVNF56SmdRmDk/r",
	"UlkfdHbhbp/9qQI/EXGCRV2CsYCmxAJymeIBs7PfVXKfN9lI/0pAkqqRUJ1//TzoP7GXNZ185aWuQymD",
	"1+bEVQb0abTLiWPbr9m/ST64B5Xaeur5jiR+h2TPGKtciWWxumkHVZ0lqblkPEYSEsiGo2Z1CdAnu0Xf",
	"+EicbsIVfe6uA9TffD0FpJ9LdLIb0UJfcZNkcb/caAE/yaWP1ZG0FlUVguE0q8qEIurAd3UHyl6bDdl0",
	"WaDacC2VT1Xqgl25xmsVkZGKIJVXnWcAxXa+W3Hl4nhVhdhVhhSRR9UlI9uV+rEfXyY2cyVgdb2XCy4G",
	"Cr7gUL1XRIt+2ZlDqlcENnrV90ro7v+2D1bsHXXhB8KbFkZj+Fse+EkuoW3R/sNEcc4dv7QX7hLNlXtF",
	"mSrRprRl2Iadj5V1T6BPe+eeW/qXwoouwcK/X6pRrGKPjBNb/2xEk7L3Sac0ouotAKY1mqYm0Gd4PXkK",
	"nlxq4AbKAjacAbeiIyStZ4UUoo7/B2Pow6cB7onl9zyR8InN233PIYyGQ/+okvTc3xjW60GxmpXtZrpF",
	"Bfskp1Nwubd0pluf6mqkPtNVbWfLsm19py+X0RExoSWs0cCiLSBdOAFftOWriyfuWQVUMyXdK8zVriPy",
	"L604s3FRYboIMfp3aP7aeVv6nlhrt643wE5vXPmYJwynlbxr/KJ3yj2gLl2yqjbgBp74Ovq/HzzDL05P",
	"4fVf2uSJq1r0Dya5/2NF/YwZdBpD5hG9sSYgLFpzcAFLmbqnfQ3jVGs0wQ0q3xpvf1rIy4WvgLrEwoCd",
	"DYpVeX1G8O/nr3+wlslluUSBpvNiU6HkEqFgSqOKKJWo6TMDGdtgFTcslUY3f4QVvq/ocZAVxizctmxY",
	"XgZqhgenfm5NqsSV17qmvXmvXnhy9uP7fuHRBgm19hv18DpjB1XFP763F48/p1DW75zlOJOKrzlVNbuO",
	"X6q35ZfSZK401QrduxcPm8rXk8nN+5v/DQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
