// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_revocations.sql

package dbsqlc

import (
	"context"
	"time"
)

const deleteExpiredAgentRevocations = `-- name: DeleteExpiredAgentRevocations :execrows
DELETE FROM agent_revocations WHERE cert_expires_at < $1
`

func (q *Queries) DeleteExpiredAgentRevocations(ctx context.Context, certExpiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAgentRevocations, certExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAgentRevocations = `-- name: ListAgentRevocations :many
SELECT agent_id, revoked_at, cert_expires_at FROM agent_revocations
`

func (q *Queries) ListAgentRevocations(ctx context.Context) ([]AgentRevocation, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRevocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRevocation
	for rows.Next() {
		var i AgentRevocation
		if err := rows.Scan(&i.AgentID, &i.RevokedAt, &i.CertExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentRevocation = `-- name: UpsertAgentRevocation :exec

INSERT INTO agent_revocations (agent_id, revoked_at, cert_expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id) DO UPDATE SET
    revoked_at = EXCLUDED.revoked_at,
    cert_expires_at = GREATEST(agent_revocations.cert_expires_at, EXCLUDED.cert_expires_at)
`

type UpsertAgentRevocationParams struct {
	AgentID       string
	RevokedAt     time.Time
	CertExpiresAt time.Time
}

// R-Q-03: agent_revocations — durable record of deregistered agents
// whose mTLS client cert is still within validity. Persisted so a
// restart cannot accidentally re-trust a revoked agent (P1-SEC-06).
// cert_expires_at is max-merged so a redundant revocation issued
// against an older cert does not shrink the window.
func (q *Queries) UpsertAgentRevocation(ctx context.Context, arg UpsertAgentRevocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentRevocation, arg.AgentID, arg.RevokedAt, arg.CertExpiresAt)
	return err
}
