// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAgents = `-- name: ListAgents :many
SELECT id, node_name, fleet_group_id, version, read_only, last_seen_at
FROM agents
ORDER BY last_seen_at DESC
`

type ListAgentsRow struct {
	ID           string
	NodeName     string
	FleetGroupID pgtype.Text
	Version      string
	ReadOnly     bool
	LastSeenAt   pgtype.Timestamptz
}

func (q *Queries) ListAgents(ctx context.Context) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeName,
			&i.FleetGroupID,
			&i.Version,
			&i.ReadOnly,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgent = `-- name: UpsertAgent :exec
INSERT INTO agents (id, node_name, fleet_group_id, version, read_only, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE
SET node_name = EXCLUDED.node_name,
    fleet_group_id = EXCLUDED.fleet_group_id,
    version = EXCLUDED.version,
    read_only = EXCLUDED.read_only,
    last_seen_at = EXCLUDED.last_seen_at
`

type UpsertAgentParams struct {
	ID           string
	NodeName     string
	FleetGroupID pgtype.Text
	Version      string
	ReadOnly     bool
	LastSeenAt   pgtype.Timestamptz
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) error {
	_, err := q.db.Exec(ctx, upsertAgent,
		arg.ID,
		arg.NodeName,
		arg.FleetGroupID,
		arg.Version,
		arg.ReadOnly,
		arg.LastSeenAt,
	)
	return err
}
