// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_config_targets.sql

package dbsqlc

import (
	"context"
	"time"
)

const deleteAgentConfigTarget = `-- name: DeleteAgentConfigTarget :execrows
DELETE FROM agent_config_targets WHERE scope_type = $1 AND scope_id = $2
`

type DeleteAgentConfigTargetParams struct {
	ScopeType string
	ScopeID   string
}

func (q *Queries) DeleteAgentConfigTarget(ctx context.Context, arg DeleteAgentConfigTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentConfigTarget, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentConfigTarget = `-- name: GetAgentConfigTarget :one

SELECT scope_type, scope_id, sections_json, created_at, updated_at
FROM agent_config_targets
WHERE scope_type = $1 AND scope_id = $2
`

type GetAgentConfigTargetParams struct {
	ScopeType string
	ScopeID   string
}

// agent_config_targets — desired Telemt config per scope (group | agent).
func (q *Queries) GetAgentConfigTarget(ctx context.Context, arg GetAgentConfigTargetParams) (AgentConfigTarget, error) {
	row := q.db.QueryRowContext(ctx, getAgentConfigTarget, arg.ScopeType, arg.ScopeID)
	var i AgentConfigTarget
	err := row.Scan(
		&i.ScopeType,
		&i.ScopeID,
		&i.SectionsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentConfigTargets = `-- name: ListAgentConfigTargets :many
SELECT scope_type, scope_id, sections_json, created_at, updated_at
FROM agent_config_targets
ORDER BY scope_type ASC, scope_id ASC
`

func (q *Queries) ListAgentConfigTargets(ctx context.Context) ([]AgentConfigTarget, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConfigTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConfigTarget
	for rows.Next() {
		var i AgentConfigTarget
		if err := rows.Scan(
			&i.ScopeType,
			&i.ScopeID,
			&i.SectionsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentConfigTarget = `-- name: UpsertAgentConfigTarget :exec
INSERT INTO agent_config_targets (scope_type, scope_id, sections_json, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scope_type, scope_id) DO UPDATE
SET sections_json = EXCLUDED.sections_json,
    updated_at    = EXCLUDED.updated_at
`

type UpsertAgentConfigTargetParams struct {
	ScopeType    string
	ScopeID      string
	SectionsJson string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpsertAgentConfigTarget(ctx context.Context, arg UpsertAgentConfigTargetParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentConfigTarget,
		arg.ScopeType,
		arg.ScopeID,
		arg.SectionsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
