// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_fallback_state.sql

package dbsqlc

import (
	"context"
)

const deleteAgentFallbackState = `-- name: DeleteAgentFallbackState :exec
DELETE FROM agent_fallback_state WHERE agent_id = $1
`

func (q *Queries) DeleteAgentFallbackState(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentFallbackState, agentID)
	return err
}

const getAgentFallbackState = `-- name: GetAgentFallbackState :one
SELECT agent_id, entered_at_unix
FROM agent_fallback_state
WHERE agent_id = $1
`

func (q *Queries) GetAgentFallbackState(ctx context.Context, agentID string) (AgentFallbackState, error) {
	row := q.db.QueryRowContext(ctx, getAgentFallbackState, agentID)
	var i AgentFallbackState
	err := row.Scan(&i.AgentID, &i.EnteredAtUnix)
	return i, err
}

const listAgentFallbackState = `-- name: ListAgentFallbackState :many
SELECT agent_id, entered_at_unix
FROM agent_fallback_state
ORDER BY entered_at_unix ASC
`

func (q *Queries) ListAgentFallbackState(ctx context.Context) ([]AgentFallbackState, error) {
	rows, err := q.db.QueryContext(ctx, listAgentFallbackState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentFallbackState
	for rows.Next() {
		var i AgentFallbackState
		if err := rows.Scan(&i.AgentID, &i.EnteredAtUnix); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putAgentFallbackState = `-- name: PutAgentFallbackState :exec
INSERT INTO agent_fallback_state (agent_id, entered_at_unix)
VALUES ($1, $2)
ON CONFLICT (agent_id) DO NOTHING
`

type PutAgentFallbackStateParams struct {
	AgentID       string
	EnteredAtUnix int64
}

func (q *Queries) PutAgentFallbackState(ctx context.Context, arg PutAgentFallbackStateParams) error {
	_, err := q.db.ExecContext(ctx, putAgentFallbackState, arg.AgentID, arg.EnteredAtUnix)
	return err
}
