// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_certificate_recovery_grants.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const getAgentCertificateRecoveryGrant = `-- name: GetAgentCertificateRecoveryGrant :one

SELECT agent_id, issued_by, issued_at, expires_at, used_at, revoked_at
FROM agent_certificate_recovery_grants
WHERE agent_id = $1
`

// R-Q-03: agent_certificate_recovery_grants — admin-issued grants
// that allow a replaced agent to bootstrap with a fresh cert.
func (q *Queries) GetAgentCertificateRecoveryGrant(ctx context.Context, agentID string) (AgentCertificateRecoveryGrant, error) {
	row := q.db.QueryRowContext(ctx, getAgentCertificateRecoveryGrant, agentID)
	var i AgentCertificateRecoveryGrant
	err := row.Scan(
		&i.AgentID,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAgentCertificateRecoveryGrants = `-- name: ListAgentCertificateRecoveryGrants :many
SELECT agent_id, issued_by, issued_at, expires_at, used_at, revoked_at
FROM agent_certificate_recovery_grants
ORDER BY issued_at ASC, agent_id ASC
`

func (q *Queries) ListAgentCertificateRecoveryGrants(ctx context.Context) ([]AgentCertificateRecoveryGrant, error) {
	rows, err := q.db.QueryContext(ctx, listAgentCertificateRecoveryGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentCertificateRecoveryGrant
	for rows.Next() {
		var i AgentCertificateRecoveryGrant
		if err := rows.Scan(
			&i.AgentID,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentCertificateRecoveryGrantUsed = `-- name: MarkAgentCertificateRecoveryGrantUsed :execrows
UPDATE agent_certificate_recovery_grants
SET used_at = $1
WHERE agent_id = $2 AND used_at IS NULL AND revoked_at IS NULL
`

type MarkAgentCertificateRecoveryGrantUsedParams struct {
	UsedAt  sql.NullTime
	AgentID string
}

func (q *Queries) MarkAgentCertificateRecoveryGrantUsed(ctx context.Context, arg MarkAgentCertificateRecoveryGrantUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAgentCertificateRecoveryGrantUsed, arg.UsedAt, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAgentCertificateRecoveryGrant = `-- name: RevokeAgentCertificateRecoveryGrant :execrows
UPDATE agent_certificate_recovery_grants
SET revoked_at = $1
WHERE agent_id = $2 AND used_at IS NULL AND revoked_at IS NULL
`

type RevokeAgentCertificateRecoveryGrantParams struct {
	RevokedAt sql.NullTime
	AgentID   string
}

func (q *Queries) RevokeAgentCertificateRecoveryGrant(ctx context.Context, arg RevokeAgentCertificateRecoveryGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAgentCertificateRecoveryGrant, arg.RevokedAt, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAgentCertificateRecoveryGrant = `-- name: UpsertAgentCertificateRecoveryGrant :exec
INSERT INTO agent_certificate_recovery_grants (agent_id, issued_by, issued_at, expires_at, used_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (agent_id) DO UPDATE
SET issued_by = EXCLUDED.issued_by,
    issued_at = EXCLUDED.issued_at,
    expires_at = EXCLUDED.expires_at,
    used_at = EXCLUDED.used_at,
    revoked_at = EXCLUDED.revoked_at
`

type UpsertAgentCertificateRecoveryGrantParams struct {
	AgentID   string
	IssuedBy  string
	IssuedAt  time.Time
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	RevokedAt sql.NullTime
}

func (q *Queries) UpsertAgentCertificateRecoveryGrant(ctx context.Context, arg UpsertAgentCertificateRecoveryGrantParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentCertificateRecoveryGrant,
		arg.AgentID,
		arg.IssuedBy,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.RevokedAt,
	)
	return err
}
