// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_events.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec

INSERT INTO audit_events (id, actor_id, action, target_id, details, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendAuditEventParams struct {
	ID        string
	ActorID   string
	Action    string
	TargetID  string
	Details   json.RawMessage
	CreatedAt time.Time
}

// R-Q-03: extend sqlc coverage to audit_events.
func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, appendAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_id, action, target_id, details, created_at
FROM (
    SELECT id, actor_id, action, target_id, details, created_at
    FROM audit_events
    ORDER BY created_at DESC, id DESC
    LIMIT $1
) sub
ORDER BY created_at, id
`

// Returns the most recent N rows in chronological order. The inner
// subquery makes the index do the heavy lifting (DESC + LIMIT) and the
// outer ORDER BY restores ascending playback order so callers can
// replay them as a timeline without an extra reverse pass.
func (q *Queries) ListAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditEvents = `-- name: PruneAuditEvents :execrows
DELETE FROM audit_events WHERE created_at < $1
`

func (q *Queries) PruneAuditEvents(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAuditEvents, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
