// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_events.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec

INSERT INTO audit_events (id, actor_id, action, target_id, details, created_at, prev_hash, event_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AppendAuditEventParams struct {
	ID        string
	ActorID   string
	Action    string
	TargetID  string
	Details   json.RawMessage
	CreatedAt time.Time
	PrevHash  string
	EventHash string
}

// R-Q-03: extend sqlc coverage to audit_events.
func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, appendAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.Details,
		arg.CreatedAt,
		arg.PrevHash,
		arg.EventHash,
	)
	return err
}

const latestAuditChainHash = `-- name: LatestAuditChainHash :one
SELECT CAST(COALESCE(
    (SELECT event_hash
       FROM audit_events
       ORDER BY created_at DESC, id DESC
       LIMIT 1),
    ''
) AS TEXT) AS hash
`

// Returns the event_hash of the most recently persisted audit row,
// or empty string when the table is empty. The batch writer reads
// this once before each flush and chains every row in the batch
// onto the tail of the existing chain.
//
// The CAST forces sqlc to infer a `string` return rather than the
// generic interface{} that COALESCE would otherwise produce — the
// column is TEXT NOT NULL in both backends, so the cast is a no-op
// at the SQL layer.
func (q *Queries) LatestAuditChainHash(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, latestAuditChainHash)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_id, action, target_id, details, created_at, prev_hash, event_hash
FROM (
    SELECT id, actor_id, action, target_id, details, created_at, prev_hash, event_hash
    FROM audit_events
    ORDER BY created_at DESC, id DESC
    LIMIT $1
) sub
ORDER BY created_at, id
`

// Returns the most recent N rows in chronological order. The inner
// subquery makes the index do the heavy lifting (DESC + LIMIT) and the
// outer ORDER BY restores ascending playback order so callers can
// replay them as a timeline without an extra reverse pass.
func (q *Queries) ListAuditEvents(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetID,
			&i.Details,
			&i.CreatedAt,
			&i.PrevHash,
			&i.EventHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditEvents = `-- name: PruneAuditEvents :execrows
DELETE FROM audit_events WHERE created_at < $1
`

func (q *Queries) PruneAuditEvents(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAuditEvents, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
