// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificate_authority.sql

package dbsqlc

import (
	"context"
	"time"
)

const getCertificateAuthority = `-- name: GetCertificateAuthority :one

SELECT ca_pem, private_key_pem, updated_at
FROM certificate_authority
WHERE scope = $1
`

type GetCertificateAuthorityRow struct {
	CaPem         string
	PrivateKeyPem string
	UpdatedAt     time.Time
}

// R-Q-03: certificate_authority — singleton row that stores the
// control-plane root CA (PEM + private-key PEM, optionally encrypted).
func (q *Queries) GetCertificateAuthority(ctx context.Context, scope string) (GetCertificateAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getCertificateAuthority, scope)
	var i GetCertificateAuthorityRow
	err := row.Scan(&i.CaPem, &i.PrivateKeyPem, &i.UpdatedAt)
	return i, err
}

const upsertCertificateAuthority = `-- name: UpsertCertificateAuthority :exec
INSERT INTO certificate_authority (scope, ca_pem, private_key_pem, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (scope) DO UPDATE
SET ca_pem = EXCLUDED.ca_pem,
    private_key_pem = EXCLUDED.private_key_pem,
    updated_at = EXCLUDED.updated_at
`

type UpsertCertificateAuthorityParams struct {
	Scope         string
	CaPem         string
	PrivateKeyPem string
	UpdatedAt     time.Time
}

func (q *Queries) UpsertCertificateAuthority(ctx context.Context, arg UpsertCertificateAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, upsertCertificateAuthority,
		arg.Scope,
		arg.CaPem,
		arg.PrivateKeyPem,
		arg.UpdatedAt,
	)
	return err
}
