// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_assignments.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteClientAssignmentsForClient = `-- name: DeleteClientAssignmentsForClient :exec
DELETE FROM client_assignments WHERE client_id = $1
`

func (q *Queries) DeleteClientAssignmentsForClient(ctx context.Context, clientID string) error {
	_, err := q.db.ExecContext(ctx, deleteClientAssignmentsForClient, clientID)
	return err
}

const insertClientAssignment = `-- name: InsertClientAssignment :exec
INSERT INTO client_assignments (id, client_id, target_type, fleet_group_id, agent_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertClientAssignmentParams struct {
	ID           string
	ClientID     string
	TargetType   string
	FleetGroupID uuid.NullUUID
	AgentID      sql.NullString
	CreatedAt    time.Time
}

func (q *Queries) InsertClientAssignment(ctx context.Context, arg InsertClientAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, insertClientAssignment,
		arg.ID,
		arg.ClientID,
		arg.TargetType,
		arg.FleetGroupID,
		arg.AgentID,
		arg.CreatedAt,
	)
	return err
}

const listAllClientAssignments = `-- name: ListAllClientAssignments :many
SELECT id, client_id, target_type, fleet_group_id, agent_id, created_at
FROM client_assignments
ORDER BY client_id ASC, created_at ASC, id ASC
`

func (q *Queries) ListAllClientAssignments(ctx context.Context) ([]ClientAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listAllClientAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientAssignment
	for rows.Next() {
		var i ClientAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TargetType,
			&i.FleetGroupID,
			&i.AgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientAssignments = `-- name: ListClientAssignments :many

SELECT id, client_id, target_type, fleet_group_id, agent_id, created_at
FROM client_assignments
WHERE client_id = $1
ORDER BY created_at ASC, id ASC
`

// R-Q-03: client_assignments — many-to-many between a managed client
// and its target (fleet group OR explicit agent).
func (q *Queries) ListClientAssignments(ctx context.Context, clientID string) ([]ClientAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listClientAssignments, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientAssignment
	for rows.Next() {
		var i ClientAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TargetType,
			&i.FleetGroupID,
			&i.AgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
