// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_ip_history.sql

package dbsqlc

import (
	"context"
	"time"
)

const listClientIPHistory = `-- name: ListClientIPHistory :many

SELECT agent_id, client_id, ip_address, first_seen, last_seen
FROM client_ip_history
WHERE client_id = $1
ORDER BY last_seen DESC
LIMIT $2
`

type ListClientIPHistoryParams struct {
	ClientID string
	Limit    int32
}

// R-Q-03: client_ip_history — durable per-(client, agent, ip) seen
// log used by the IP history card.
// P-7: row count is capped by $2 (callers pass storage.DefaultListLimit) so
// a high-cardinality client cannot stream millions of raw rows. The Go-side
// timeseries helpers in storage/{sqlite,postgres} apply additional [from,
// to] window filters; this raw sqlc query is currently unused but is kept
// in sync to prevent reintroducing an unbounded scan when it is wired up.
func (q *Queries) ListClientIPHistory(ctx context.Context, arg ListClientIPHistoryParams) ([]ClientIpHistory, error) {
	rows, err := q.db.QueryContext(ctx, listClientIPHistory, arg.ClientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientIpHistory
	for rows.Next() {
		var i ClientIpHistory
		if err := rows.Scan(
			&i.AgentID,
			&i.ClientID,
			&i.IpAddress,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneClientIPHistory = `-- name: PruneClientIPHistory :execrows
DELETE FROM client_ip_history WHERE last_seen < $1
`

func (q *Queries) PruneClientIPHistory(ctx context.Context, lastSeen time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneClientIPHistory, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertClientIPHistory = `-- name: UpsertClientIPHistory :exec
INSERT INTO client_ip_history (agent_id, client_id, ip_address, first_seen, last_seen)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (agent_id, client_id, ip_address) DO UPDATE
SET last_seen = EXCLUDED.last_seen
`

type UpsertClientIPHistoryParams struct {
	AgentID   string
	ClientID  string
	IpAddress string
	FirstSeen time.Time
	LastSeen  time.Time
}

func (q *Queries) UpsertClientIPHistory(ctx context.Context, arg UpsertClientIPHistoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertClientIPHistory,
		arg.AgentID,
		arg.ClientID,
		arg.IpAddress,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
