// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_usage.sql

package dbsqlc

import (
	"context"
	"time"
)

const deleteClientUsageByClient = `-- name: DeleteClientUsageByClient :exec
DELETE FROM client_usage WHERE client_id = $1
`

func (q *Queries) DeleteClientUsageByClient(ctx context.Context, clientID string) error {
	_, err := q.db.ExecContext(ctx, deleteClientUsageByClient, clientID)
	return err
}

const listAllClientUsage = `-- name: ListAllClientUsage :many

SELECT client_id, agent_id, traffic_used_bytes, unique_ips_used,
       active_tcp_conns, active_unique_ips, observed_at,
       quota_used_bytes, quota_last_reset_unix, agent_boot_id,
       last_total_bytes
FROM client_usage
ORDER BY client_id ASC, agent_id ASC
`

// R-Q-03: client_usage — per-(client, agent) usage counters reported
// back from agents.
func (q *Queries) ListAllClientUsage(ctx context.Context) ([]ClientUsage, error) {
	rows, err := q.db.QueryContext(ctx, listAllClientUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientUsage
	for rows.Next() {
		var i ClientUsage
		if err := rows.Scan(
			&i.ClientID,
			&i.AgentID,
			&i.TrafficUsedBytes,
			&i.UniqueIpsUsed,
			&i.ActiveTcpConns,
			&i.ActiveUniqueIps,
			&i.ObservedAt,
			&i.QuotaUsedBytes,
			&i.QuotaLastResetUnix,
			&i.AgentBootID,
			&i.LastTotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClientUsage = `-- name: UpsertClientUsage :exec
INSERT INTO client_usage (client_id, agent_id, traffic_used_bytes,
                          unique_ips_used, active_tcp_conns,
                          active_unique_ips, quota_used_bytes,
                          quota_last_reset_unix, observed_at,
                          agent_boot_id, last_total_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (client_id, agent_id) DO UPDATE
SET traffic_used_bytes    = EXCLUDED.traffic_used_bytes,
    unique_ips_used       = EXCLUDED.unique_ips_used,
    active_tcp_conns      = EXCLUDED.active_tcp_conns,
    active_unique_ips     = EXCLUDED.active_unique_ips,
    quota_used_bytes      = EXCLUDED.quota_used_bytes,
    quota_last_reset_unix = EXCLUDED.quota_last_reset_unix,
    observed_at           = EXCLUDED.observed_at,
    agent_boot_id         = EXCLUDED.agent_boot_id,
    last_total_bytes      = EXCLUDED.last_total_bytes
`

type UpsertClientUsageParams struct {
	ClientID           string
	AgentID            string
	TrafficUsedBytes   int64
	UniqueIpsUsed      int32
	ActiveTcpConns     int32
	ActiveUniqueIps    int32
	QuotaUsedBytes     int64
	QuotaLastResetUnix int64
	ObservedAt         time.Time
	AgentBootID        string
	LastTotalBytes     int64
}

// P4: traffic_used_bytes is the panel-accumulated absolute (the usage
// mirror is the single owner; this row is pure write-through), and
// (agent_boot_id, last_total_bytes) is the cumulative-counter watermark
// used to derive deltas. The upsert is unconditional last-write-wins:
// ordering/duplicate protection happens upstream against the watermark
// (server.mergeClientUsageBatch), not in SQL.
func (q *Queries) UpsertClientUsage(ctx context.Context, arg UpsertClientUsageParams) error {
	_, err := q.db.ExecContext(ctx, upsertClientUsage,
		arg.ClientID,
		arg.AgentID,
		arg.TrafficUsedBytes,
		arg.UniqueIpsUsed,
		arg.ActiveTcpConns,
		arg.ActiveUniqueIps,
		arg.QuotaUsedBytes,
		arg.QuotaLastResetUnix,
		arg.ObservedAt,
		arg.AgentBootID,
		arg.LastTotalBytes,
	)
	return err
}
