// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const getClient = `-- name: GetClient :one

SELECT id, name, secret_ciphertext, user_ad_tag, enabled, max_tcp_conns,
       max_unique_ips, data_quota_bytes, expiration_rfc3339,
       created_at, updated_at, deleted_at
FROM clients
WHERE id = $1 AND deleted_at IS NULL
`

// R-Q-03: clients — managed-client core record. The `clients` group of
// tables (assignments, deployments, usage, ip_history) gets one query
// file per table; this file owns the parent.
func (q *Queries) GetClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretCiphertext,
		&i.UserAdTag,
		&i.Enabled,
		&i.MaxTcpConns,
		&i.MaxUniqueIps,
		&i.DataQuotaBytes,
		&i.ExpirationRfc3339,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, secret_ciphertext, user_ad_tag, enabled, max_tcp_conns,
       max_unique_ips, data_quota_bytes, expiration_rfc3339,
       created_at, updated_at, deleted_at
FROM clients
WHERE deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SecretCiphertext,
			&i.UserAdTag,
			&i.Enabled,
			&i.MaxTcpConns,
			&i.MaxUniqueIps,
			&i.DataQuotaBytes,
			&i.ExpirationRfc3339,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteClient = `-- name: SoftDeleteClient :execrows
UPDATE clients SET deleted_at = $2, updated_at = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteClientParams struct {
	ID        string
	DeletedAt sql.NullTime
}

func (q *Queries) SoftDeleteClient(ctx context.Context, arg SoftDeleteClientParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteClient, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertClient = `-- name: UpsertClient :exec
INSERT INTO clients (id, name, secret_ciphertext, user_ad_tag, enabled,
                     max_tcp_conns, max_unique_ips, data_quota_bytes,
                     expiration_rfc3339, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE
SET name              = EXCLUDED.name,
    secret_ciphertext = EXCLUDED.secret_ciphertext,
    user_ad_tag       = EXCLUDED.user_ad_tag,
    enabled           = EXCLUDED.enabled,
    max_tcp_conns     = EXCLUDED.max_tcp_conns,
    max_unique_ips    = EXCLUDED.max_unique_ips,
    data_quota_bytes  = EXCLUDED.data_quota_bytes,
    expiration_rfc3339 = EXCLUDED.expiration_rfc3339,
    updated_at        = EXCLUDED.updated_at,
    deleted_at        = NULL
`

type UpsertClientParams struct {
	ID                string
	Name              string
	SecretCiphertext  string
	UserAdTag         string
	Enabled           bool
	MaxTcpConns       int64
	MaxUniqueIps      int64
	DataQuotaBytes    int64
	ExpirationRfc3339 string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertClient,
		arg.ID,
		arg.Name,
		arg.SecretCiphertext,
		arg.UserAdTag,
		arg.Enabled,
		arg.MaxTcpConns,
		arg.MaxUniqueIps,
		arg.DataQuotaBytes,
		arg.ExpirationRfc3339,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
