// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_usage.sql

package dbsqlc

import (
	"context"
	"time"
)

const listAllClientUsage = `-- name: ListAllClientUsage :many
SELECT client_id, agent_id, traffic_used_bytes, unique_ips_used,
       active_tcp_conns, active_unique_ips, last_seq, observed_at
FROM client_usage
ORDER BY client_id ASC, agent_id ASC
`

func (q *Queries) ListAllClientUsage(ctx context.Context) ([]ClientUsage, error) {
	rows, err := q.db.QueryContext(ctx, listAllClientUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientUsage
	for rows.Next() {
		var i ClientUsage
		if err := rows.Scan(
			&i.ClientID,
			&i.AgentID,
			&i.TrafficUsedBytes,
			&i.UniqueIpsUsed,
			&i.ActiveTcpConns,
			&i.ActiveUniqueIps,
			&i.LastSeq,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientUsageForClient = `-- name: ListClientUsageForClient :many

SELECT client_id, agent_id, traffic_used_bytes, unique_ips_used,
       active_tcp_conns, active_unique_ips, last_seq, observed_at
FROM client_usage
WHERE client_id = $1
`

// R-Q-03: client_usage — per-(client, agent) usage counters reported
// back from agents.
func (q *Queries) ListClientUsageForClient(ctx context.Context, clientID string) ([]ClientUsage, error) {
	rows, err := q.db.QueryContext(ctx, listClientUsageForClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientUsage
	for rows.Next() {
		var i ClientUsage
		if err := rows.Scan(
			&i.ClientID,
			&i.AgentID,
			&i.TrafficUsedBytes,
			&i.UniqueIpsUsed,
			&i.ActiveTcpConns,
			&i.ActiveUniqueIps,
			&i.LastSeq,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClientUsage = `-- name: UpsertClientUsage :exec
INSERT INTO client_usage (client_id, agent_id, traffic_used_bytes,
                          unique_ips_used, active_tcp_conns,
                          active_unique_ips, last_seq, observed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (client_id, agent_id) DO UPDATE
SET traffic_used_bytes = EXCLUDED.traffic_used_bytes,
    unique_ips_used    = EXCLUDED.unique_ips_used,
    active_tcp_conns   = EXCLUDED.active_tcp_conns,
    active_unique_ips  = EXCLUDED.active_unique_ips,
    last_seq           = EXCLUDED.last_seq,
    observed_at        = EXCLUDED.observed_at
`

type UpsertClientUsageParams struct {
	ClientID         string
	AgentID          string
	TrafficUsedBytes int64
	UniqueIpsUsed    int32
	ActiveTcpConns   int32
	ActiveUniqueIps  int32
	LastSeq          int64
	ObservedAt       time.Time
}

func (q *Queries) UpsertClientUsage(ctx context.Context, arg UpsertClientUsageParams) error {
	_, err := q.db.ExecContext(ctx, upsertClientUsage,
		arg.ClientID,
		arg.AgentID,
		arg.TrafficUsedBytes,
		arg.UniqueIpsUsed,
		arg.ActiveTcpConns,
		arg.ActiveUniqueIps,
		arg.LastSeq,
		arg.ObservedAt,
	)
	return err
}
