// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_deployments.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const deleteClientDeploymentsForClient = `-- name: DeleteClientDeploymentsForClient :exec
DELETE FROM client_deployments WHERE client_id = $1
`

func (q *Queries) DeleteClientDeploymentsForClient(ctx context.Context, clientID string) error {
	_, err := q.db.ExecContext(ctx, deleteClientDeploymentsForClient, clientID)
	return err
}

const listClientDeployments = `-- name: ListClientDeployments :many

SELECT client_id, agent_id, desired_operation, status, last_error,
       connection_links, link_diagnostic, last_applied_at, updated_at,
       last_reset_epoch_secs
FROM client_deployments
WHERE client_id = $1
ORDER BY agent_id ASC
`

type ListClientDeploymentsRow struct {
	ClientID           string
	AgentID            string
	DesiredOperation   string
	Status             string
	LastError          string
	ConnectionLinks    json.RawMessage
	LinkDiagnostic     string
	LastAppliedAt      sql.NullTime
	UpdatedAt          time.Time
	LastResetEpochSecs int64
}

// R-Q-03: client_deployments — per-(client, agent) deployment state
// + connection link returned by the agent.
func (q *Queries) ListClientDeployments(ctx context.Context, clientID string) ([]ListClientDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClientDeployments, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientDeploymentsRow
	for rows.Next() {
		var i ListClientDeploymentsRow
		if err := rows.Scan(
			&i.ClientID,
			&i.AgentID,
			&i.DesiredOperation,
			&i.Status,
			&i.LastError,
			&i.ConnectionLinks,
			&i.LinkDiagnostic,
			&i.LastAppliedAt,
			&i.UpdatedAt,
			&i.LastResetEpochSecs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClientDeployment = `-- name: UpsertClientDeployment :exec
INSERT INTO client_deployments (client_id, agent_id, desired_operation,
                                status, last_error, connection_links,
                                link_diagnostic,
                                last_applied_at, updated_at,
                                last_reset_epoch_secs)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (client_id, agent_id) DO UPDATE
SET desired_operation = EXCLUDED.desired_operation,
    status            = EXCLUDED.status,
    last_error        = EXCLUDED.last_error,
    connection_links   = EXCLUDED.connection_links,
    link_diagnostic   = EXCLUDED.link_diagnostic,
    last_applied_at   = EXCLUDED.last_applied_at,
    updated_at        = EXCLUDED.updated_at,
    last_reset_epoch_secs = EXCLUDED.last_reset_epoch_secs
`

type UpsertClientDeploymentParams struct {
	ClientID           string
	AgentID            string
	DesiredOperation   string
	Status             string
	LastError          string
	ConnectionLinks    json.RawMessage
	LinkDiagnostic     string
	LastAppliedAt      sql.NullTime
	UpdatedAt          time.Time
	LastResetEpochSecs int64
}

func (q *Queries) UpsertClientDeployment(ctx context.Context, arg UpsertClientDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, upsertClientDeployment,
		arg.ClientID,
		arg.AgentID,
		arg.DesiredOperation,
		arg.Status,
		arg.LastError,
		arg.ConnectionLinks,
		arg.LinkDiagnostic,
		arg.LastAppliedAt,
		arg.UpdatedAt,
		arg.LastResetEpochSecs,
	)
	return err
}
