// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config_apply_batches.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTerminalConfigApplyBatches = `-- name: DeleteTerminalConfigApplyBatches :execrows
DELETE FROM config_apply_batches
WHERE status IN ('succeeded', 'failed', 'halted')
  AND updated_at < $1
`

func (q *Queries) DeleteTerminalConfigApplyBatches(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTerminalConfigApplyBatches, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveConfigApplyBatchForGroup = `-- name: GetActiveConfigApplyBatchForGroup :one
SELECT id, fleet_group_id::text AS fleet_group_id, mode, wave_size, expected_revision, status, created_at, updated_at
FROM config_apply_batches
WHERE fleet_group_id = $1 AND status = 'running'
ORDER BY created_at ASC, id ASC
LIMIT 1
`

type GetActiveConfigApplyBatchForGroupRow struct {
	ID               string
	FleetGroupID     string
	Mode             string
	WaveSize         int32
	ExpectedRevision string
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetActiveConfigApplyBatchForGroup(ctx context.Context, fleetGroupID uuid.UUID) (GetActiveConfigApplyBatchForGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveConfigApplyBatchForGroup, fleetGroupID)
	var i GetActiveConfigApplyBatchForGroupRow
	err := row.Scan(
		&i.ID,
		&i.FleetGroupID,
		&i.Mode,
		&i.WaveSize,
		&i.ExpectedRevision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfigApplyBatch = `-- name: GetConfigApplyBatch :one
SELECT id, fleet_group_id::text AS fleet_group_id, mode, wave_size, expected_revision, status, created_at, updated_at
FROM config_apply_batches
WHERE id = $1
`

type GetConfigApplyBatchRow struct {
	ID               string
	FleetGroupID     string
	Mode             string
	WaveSize         int32
	ExpectedRevision string
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetConfigApplyBatch(ctx context.Context, id string) (GetConfigApplyBatchRow, error) {
	row := q.db.QueryRowContext(ctx, getConfigApplyBatch, id)
	var i GetConfigApplyBatchRow
	err := row.Scan(
		&i.ID,
		&i.FleetGroupID,
		&i.Mode,
		&i.WaveSize,
		&i.ExpectedRevision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConfigApplyBatch = `-- name: InsertConfigApplyBatch :exec

INSERT INTO config_apply_batches
    (id, fleet_group_id, mode, wave_size, expected_revision, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertConfigApplyBatchParams struct {
	ID               string
	FleetGroupID     uuid.UUID
	Mode             string
	WaveSize         int32
	ExpectedRevision string
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// config_apply_batches / config_apply_batch_targets — group-wide config-apply
// rollout batches and their per-agent delivery records. fleet_group_id is
// bound as a real uuid.UUID param (see storage/postgres/config_apply_batches.go)
// and read back cast to text so the storage layer stays a plain Go string on
// both engines, mirroring user_fleet_group_scopes.sql.
func (q *Queries) InsertConfigApplyBatch(ctx context.Context, arg InsertConfigApplyBatchParams) error {
	_, err := q.db.ExecContext(ctx, insertConfigApplyBatch,
		arg.ID,
		arg.FleetGroupID,
		arg.Mode,
		arg.WaveSize,
		arg.ExpectedRevision,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertConfigApplyBatchTarget = `-- name: InsertConfigApplyBatchTarget :exec
INSERT INTO config_apply_batch_targets (batch_id, agent_id, wave_index, job_id, status, message)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertConfigApplyBatchTargetParams struct {
	BatchID   string
	AgentID   string
	WaveIndex int32
	JobID     string
	Status    string
	Message   string
}

func (q *Queries) InsertConfigApplyBatchTarget(ctx context.Context, arg InsertConfigApplyBatchTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertConfigApplyBatchTarget,
		arg.BatchID,
		arg.AgentID,
		arg.WaveIndex,
		arg.JobID,
		arg.Status,
		arg.Message,
	)
	return err
}

const listConfigApplyBatchTargets = `-- name: ListConfigApplyBatchTargets :many
SELECT batch_id, agent_id, wave_index, job_id, status, message
FROM config_apply_batch_targets
WHERE batch_id = $1
ORDER BY wave_index ASC, agent_id ASC
`

func (q *Queries) ListConfigApplyBatchTargets(ctx context.Context, batchID string) ([]ConfigApplyBatchTarget, error) {
	rows, err := q.db.QueryContext(ctx, listConfigApplyBatchTargets, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigApplyBatchTarget
	for rows.Next() {
		var i ConfigApplyBatchTarget
		if err := rows.Scan(
			&i.BatchID,
			&i.AgentID,
			&i.WaveIndex,
			&i.JobID,
			&i.Status,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningConfigApplyBatches = `-- name: ListRunningConfigApplyBatches :many
SELECT id, fleet_group_id::text AS fleet_group_id, mode, wave_size, expected_revision, status, created_at, updated_at
FROM config_apply_batches
WHERE status = 'running'
ORDER BY created_at ASC, id ASC
`

type ListRunningConfigApplyBatchesRow struct {
	ID               string
	FleetGroupID     string
	Mode             string
	WaveSize         int32
	ExpectedRevision string
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListRunningConfigApplyBatches(ctx context.Context) ([]ListRunningConfigApplyBatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningConfigApplyBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningConfigApplyBatchesRow
	for rows.Next() {
		var i ListRunningConfigApplyBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.FleetGroupID,
			&i.Mode,
			&i.WaveSize,
			&i.ExpectedRevision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConfigApplyBatchTargetJob = `-- name: SetConfigApplyBatchTargetJob :exec
UPDATE config_apply_batch_targets
SET job_id = $1, status = $2
WHERE batch_id = $3 AND agent_id = $4
`

type SetConfigApplyBatchTargetJobParams struct {
	JobID   string
	Status  string
	BatchID string
	AgentID string
}

func (q *Queries) SetConfigApplyBatchTargetJob(ctx context.Context, arg SetConfigApplyBatchTargetJobParams) error {
	_, err := q.db.ExecContext(ctx, setConfigApplyBatchTargetJob,
		arg.JobID,
		arg.Status,
		arg.BatchID,
		arg.AgentID,
	)
	return err
}

const updateConfigApplyBatchStatus = `-- name: UpdateConfigApplyBatchStatus :execrows
UPDATE config_apply_batches
SET status = $1, updated_at = $2
WHERE id = $3
`

type UpdateConfigApplyBatchStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateConfigApplyBatchStatus(ctx context.Context, arg UpdateConfigApplyBatchStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateConfigApplyBatchStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateConfigApplyBatchTargetStatus = `-- name: UpdateConfigApplyBatchTargetStatus :exec
UPDATE config_apply_batch_targets
SET status = $1, message = $2
WHERE batch_id = $3 AND agent_id = $4
`

type UpdateConfigApplyBatchTargetStatusParams struct {
	Status  string
	Message string
	BatchID string
	AgentID string
}

func (q *Queries) UpdateConfigApplyBatchTargetStatus(ctx context.Context, arg UpdateConfigApplyBatchTargetStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateConfigApplyBatchTargetStatus,
		arg.Status,
		arg.Message,
		arg.BatchID,
		arg.AgentID,
	)
	return err
}
