// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumed_totp.sql

package dbsqlc

import (
	"context"
	"time"
)

const deleteExpiredConsumedTotp = `-- name: DeleteExpiredConsumedTotp :exec
DELETE FROM consumed_totp WHERE used_at < $1
`

func (q *Queries) DeleteExpiredConsumedTotp(ctx context.Context, usedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredConsumedTotp, usedAt)
	return err
}

const listConsumedTotp = `-- name: ListConsumedTotp :many
SELECT user_id, code, used_at FROM consumed_totp
`

func (q *Queries) ListConsumedTotp(ctx context.Context) ([]ConsumedTotp, error) {
	rows, err := q.db.QueryContext(ctx, listConsumedTotp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsumedTotp
	for rows.Next() {
		var i ConsumedTotp
		if err := rows.Scan(&i.UserID, &i.Code, &i.UsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConsumedTotp = `-- name: UpsertConsumedTotp :exec

INSERT INTO consumed_totp (user_id, code, used_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, code) DO UPDATE SET used_at = EXCLUDED.used_at
`

type UpsertConsumedTotpParams struct {
	UserID string
	Code   string
	UsedAt time.Time
}

// R-Q-03: consumed_totp — replay-protection log for verified TOTP codes.
func (q *Queries) UpsertConsumedTotp(ctx context.Context, arg UpsertConsumedTotpParams) error {
	_, err := q.db.ExecContext(ctx, upsertConsumedTotp, arg.UserID, arg.Code, arg.UsedAt)
	return err
}
