// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cp_secrets.sql

package dbsqlc

import (
	"context"
	"time"
)

const getCPSecret = `-- name: GetCPSecret :one

SELECT value FROM cp_secrets WHERE key = $1
`

// R-Q-03: cp_secrets — control-plane key/value secret store.
func (q *Queries) GetCPSecret(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getCPSecret, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const upsertCPSecret = `-- name: UpsertCPSecret :exec
INSERT INTO cp_secrets (key, value, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = EXCLUDED.updated_at
`

type UpsertCPSecretParams struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}

func (q *Queries) UpsertCPSecret(ctx context.Context, arg UpsertCPSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertCPSecret, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
