// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovered_clients.sql

package dbsqlc

import (
	"context"
	"time"
)

const deleteDiscoveredClient = `-- name: DeleteDiscoveredClient :execrows
DELETE FROM discovered_clients WHERE id = $1
`

func (q *Queries) DeleteDiscoveredClient(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDiscoveredClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDiscoveredClient = `-- name: GetDiscoveredClient :one

SELECT id, agent_id, client_name, secret, status, total_octets,
       current_connections, active_unique_ips, connection_link,
       max_tcp_conns, max_unique_ips, data_quota_bytes, expiration,
       discovered_at, updated_at
FROM discovered_clients
WHERE id = $1
`

// R-Q-03: discovered_clients — agent-reported user records pending
// adoption.
func (q *Queries) GetDiscoveredClient(ctx context.Context, id string) (DiscoveredClient, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveredClient, id)
	var i DiscoveredClient
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ClientName,
		&i.Secret,
		&i.Status,
		&i.TotalOctets,
		&i.CurrentConnections,
		&i.ActiveUniqueIps,
		&i.ConnectionLink,
		&i.MaxTcpConns,
		&i.MaxUniqueIps,
		&i.DataQuotaBytes,
		&i.Expiration,
		&i.DiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiscoveredClientByAgentAndName = `-- name: GetDiscoveredClientByAgentAndName :one
SELECT id, agent_id, client_name, secret, status, total_octets,
       current_connections, active_unique_ips, connection_link,
       max_tcp_conns, max_unique_ips, data_quota_bytes, expiration,
       discovered_at, updated_at
FROM discovered_clients
WHERE agent_id = $1 AND client_name = $2
`

type GetDiscoveredClientByAgentAndNameParams struct {
	AgentID    string
	ClientName string
}

func (q *Queries) GetDiscoveredClientByAgentAndName(ctx context.Context, arg GetDiscoveredClientByAgentAndNameParams) (DiscoveredClient, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveredClientByAgentAndName, arg.AgentID, arg.ClientName)
	var i DiscoveredClient
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ClientName,
		&i.Secret,
		&i.Status,
		&i.TotalOctets,
		&i.CurrentConnections,
		&i.ActiveUniqueIps,
		&i.ConnectionLink,
		&i.MaxTcpConns,
		&i.MaxUniqueIps,
		&i.DataQuotaBytes,
		&i.Expiration,
		&i.DiscoveredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiscoveredClients = `-- name: ListDiscoveredClients :many
SELECT id, agent_id, client_name, secret, status, total_octets,
       current_connections, active_unique_ips, connection_link,
       max_tcp_conns, max_unique_ips, data_quota_bytes, expiration,
       discovered_at, updated_at
FROM discovered_clients
ORDER BY discovered_at DESC, id
`

func (q *Queries) ListDiscoveredClients(ctx context.Context) ([]DiscoveredClient, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveredClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveredClient
	for rows.Next() {
		var i DiscoveredClient
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ClientName,
			&i.Secret,
			&i.Status,
			&i.TotalOctets,
			&i.CurrentConnections,
			&i.ActiveUniqueIps,
			&i.ConnectionLink,
			&i.MaxTcpConns,
			&i.MaxUniqueIps,
			&i.DataQuotaBytes,
			&i.Expiration,
			&i.DiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscoveredClientStatus = `-- name: UpdateDiscoveredClientStatus :execrows
UPDATE discovered_clients SET status = $2, updated_at = $3 WHERE id = $1
`

type UpdateDiscoveredClientStatusParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateDiscoveredClientStatus(ctx context.Context, arg UpdateDiscoveredClientStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDiscoveredClientStatus, arg.ID, arg.Status, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDiscoveredClient = `-- name: UpsertDiscoveredClient :exec
INSERT INTO discovered_clients (id, agent_id, client_name, secret, status,
                                total_octets, current_connections,
                                active_unique_ips, connection_link,
                                max_tcp_conns, max_unique_ips,
                                data_quota_bytes, expiration,
                                discovered_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE
SET secret              = EXCLUDED.secret,
    status              = EXCLUDED.status,
    total_octets        = EXCLUDED.total_octets,
    current_connections = EXCLUDED.current_connections,
    active_unique_ips   = EXCLUDED.active_unique_ips,
    connection_link     = EXCLUDED.connection_link,
    max_tcp_conns       = EXCLUDED.max_tcp_conns,
    max_unique_ips      = EXCLUDED.max_unique_ips,
    data_quota_bytes    = EXCLUDED.data_quota_bytes,
    expiration          = EXCLUDED.expiration,
    discovered_at       = EXCLUDED.discovered_at,
    updated_at          = EXCLUDED.updated_at
`

type UpsertDiscoveredClientParams struct {
	ID                 string
	AgentID            string
	ClientName         string
	Secret             string
	Status             string
	TotalOctets        int64
	CurrentConnections int32
	ActiveUniqueIps    int32
	ConnectionLink     string
	MaxTcpConns        int32
	MaxUniqueIps       int32
	DataQuotaBytes     int64
	Expiration         string
	DiscoveredAt       time.Time
	UpdatedAt          time.Time
}

func (q *Queries) UpsertDiscoveredClient(ctx context.Context, arg UpsertDiscoveredClientParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoveredClient,
		arg.ID,
		arg.AgentID,
		arg.ClientName,
		arg.Secret,
		arg.Status,
		arg.TotalOctets,
		arg.CurrentConnections,
		arg.ActiveUniqueIps,
		arg.ConnectionLink,
		arg.MaxTcpConns,
		arg.MaxUniqueIps,
		arg.DataQuotaBytes,
		arg.Expiration,
		arg.DiscoveredAt,
		arg.UpdatedAt,
	)
	return err
}
