// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollment_tokens.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :execrows
UPDATE enrollment_tokens
SET consumed_at = $1
WHERE value = $2 AND consumed_at IS NULL AND revoked_at IS NULL
`

type ConsumeEnrollmentTokenParams struct {
	ConsumedAt sql.NullTime
	Value      string
}

func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, arg ConsumeEnrollmentTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeEnrollmentToken, arg.ConsumedAt, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEnrollmentToken = `-- name: GetEnrollmentToken :one

SELECT value, fleet_group_id, issued_at, expires_at, consumed_at, revoked_at
FROM enrollment_tokens
WHERE value = $1
`

type GetEnrollmentTokenRow struct {
	Value        string
	FleetGroupID uuid.NullUUID
	IssuedAt     time.Time
	ExpiresAt    time.Time
	ConsumedAt   sql.NullTime
	RevokedAt    sql.NullTime
}

// R-Q-03: extend sqlc coverage to enrollment_tokens. value_hash
// (migration 0021) is not yet read or written by Go code — it has a ”
// default so the upsert below leaves it untouched. When a future
// caller needs the hash, the SELECTs and INSERT can be widened in one
// place.
func (q *Queries) GetEnrollmentToken(ctx context.Context, value string) (GetEnrollmentTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentToken, value)
	var i GetEnrollmentTokenRow
	err := row.Scan(
		&i.Value,
		&i.FleetGroupID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listEnrollmentTokens = `-- name: ListEnrollmentTokens :many
SELECT value, fleet_group_id, issued_at, expires_at, consumed_at, revoked_at
FROM enrollment_tokens
ORDER BY issued_at, value
`

type ListEnrollmentTokensRow struct {
	Value        string
	FleetGroupID uuid.NullUUID
	IssuedAt     time.Time
	ExpiresAt    time.Time
	ConsumedAt   sql.NullTime
	RevokedAt    sql.NullTime
}

func (q *Queries) ListEnrollmentTokens(ctx context.Context) ([]ListEnrollmentTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentTokensRow
	for rows.Next() {
		var i ListEnrollmentTokensRow
		if err := rows.Scan(
			&i.Value,
			&i.FleetGroupID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeEnrollmentToken = `-- name: RevokeEnrollmentToken :execrows
UPDATE enrollment_tokens
SET revoked_at = $1
WHERE value = $2 AND consumed_at IS NULL AND revoked_at IS NULL
`

type RevokeEnrollmentTokenParams struct {
	RevokedAt sql.NullTime
	Value     string
}

func (q *Queries) RevokeEnrollmentToken(ctx context.Context, arg RevokeEnrollmentTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeEnrollmentToken, arg.RevokedAt, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEnrollmentToken = `-- name: UpsertEnrollmentToken :exec
INSERT INTO enrollment_tokens (value, fleet_group_id, issued_at, expires_at, consumed_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (value) DO UPDATE
SET fleet_group_id = EXCLUDED.fleet_group_id,
    issued_at = EXCLUDED.issued_at,
    expires_at = EXCLUDED.expires_at,
    consumed_at = EXCLUDED.consumed_at,
    revoked_at = EXCLUDED.revoked_at
`

type UpsertEnrollmentTokenParams struct {
	Value        string
	FleetGroupID uuid.NullUUID
	IssuedAt     time.Time
	ExpiresAt    time.Time
	ConsumedAt   sql.NullTime
	RevokedAt    sql.NullTime
}

func (q *Queries) UpsertEnrollmentToken(ctx context.Context, arg UpsertEnrollmentTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertEnrollmentToken,
		arg.Value,
		arg.FleetGroupID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.RevokedAt,
	)
	return err
}
