// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fleet_group_integrations.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteFleetGroupIntegration = `-- name: DeleteFleetGroupIntegration :execrows
DELETE FROM fleet_group_integrations WHERE id = $1
`

func (q *Queries) DeleteFleetGroupIntegration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFleetGroupIntegration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFleetGroupIntegration = `-- name: GetFleetGroupIntegration :one

SELECT id, fleet_group_id, kind, provider_id, config, enabled,
       created_at, updated_at
FROM fleet_group_integrations
WHERE id = $1
`

// R-Q-03: fleet_group_integrations — per-fleet-group provider hookup.
func (q *Queries) GetFleetGroupIntegration(ctx context.Context, id uuid.UUID) (FleetGroupIntegration, error) {
	row := q.db.QueryRowContext(ctx, getFleetGroupIntegration, id)
	var i FleetGroupIntegration
	err := row.Scan(
		&i.ID,
		&i.FleetGroupID,
		&i.Kind,
		&i.ProviderID,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFleetGroupIntegrations = `-- name: ListFleetGroupIntegrations :many
SELECT id, fleet_group_id, kind, provider_id, config, enabled,
       created_at, updated_at
FROM fleet_group_integrations
WHERE fleet_group_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListFleetGroupIntegrations(ctx context.Context, fleetGroupID uuid.UUID) ([]FleetGroupIntegration, error) {
	rows, err := q.db.QueryContext(ctx, listFleetGroupIntegrations, fleetGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FleetGroupIntegration
	for rows.Next() {
		var i FleetGroupIntegration
		if err := rows.Scan(
			&i.ID,
			&i.FleetGroupID,
			&i.Kind,
			&i.ProviderID,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFleetGroupIntegration = `-- name: UpsertFleetGroupIntegration :exec
INSERT INTO fleet_group_integrations (id, fleet_group_id, kind, provider_id,
                                      config, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET kind        = EXCLUDED.kind,
    provider_id = EXCLUDED.provider_id,
    config      = EXCLUDED.config,
    enabled     = EXCLUDED.enabled,
    updated_at  = EXCLUDED.updated_at
`

type UpsertFleetGroupIntegrationParams struct {
	ID           uuid.UUID
	FleetGroupID uuid.UUID
	Kind         string
	ProviderID   uuid.NullUUID
	Config       json.RawMessage
	Enabled      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpsertFleetGroupIntegration(ctx context.Context, arg UpsertFleetGroupIntegrationParams) error {
	_, err := q.db.ExecContext(ctx, upsertFleetGroupIntegration,
		arg.ID,
		arg.FleetGroupID,
		arg.Kind,
		arg.ProviderID,
		arg.Config,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
