// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fleet_groups.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFleetGroup = `-- name: CreateFleetGroup :exec
INSERT INTO fleet_groups (id, name, label, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateFleetGroupParams struct {
	ID          uuid.UUID
	Name        string
	Label       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateFleetGroup(ctx context.Context, arg CreateFleetGroupParams) error {
	_, err := q.db.ExecContext(ctx, createFleetGroup,
		arg.ID,
		arg.Name,
		arg.Label,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFleetGroup = `-- name: DeleteFleetGroup :execrows
DELETE FROM fleet_groups WHERE id = $1
`

func (q *Queries) DeleteFleetGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFleetGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFleetGroup = `-- name: GetFleetGroup :one

SELECT id, name, label, description, created_at, updated_at
FROM fleet_groups
WHERE id = $1
`

type GetFleetGroupRow struct {
	ID          uuid.UUID
	Name        string
	Label       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// R-Q-03: fleet_groups — operator-managed grouping of agents +
// enrollment-tokens + client-assignments. Note: id is UUID on
// postgres (UUID id column).
func (q *Queries) GetFleetGroup(ctx context.Context, id uuid.UUID) (GetFleetGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getFleetGroup, id)
	var i GetFleetGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFleetGroupByName = `-- name: GetFleetGroupByName :one
SELECT id, name, label, description, created_at, updated_at
FROM fleet_groups
WHERE name = $1
`

type GetFleetGroupByNameRow struct {
	ID          uuid.UUID
	Name        string
	Label       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetFleetGroupByName(ctx context.Context, name string) (GetFleetGroupByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getFleetGroupByName, name)
	var i GetFleetGroupByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Label,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFleetGroups = `-- name: ListFleetGroups :many
SELECT id, name, label, description, created_at, updated_at
FROM fleet_groups
ORDER BY created_at ASC, id ASC
`

type ListFleetGroupsRow struct {
	ID          uuid.UUID
	Name        string
	Label       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListFleetGroups(ctx context.Context) ([]ListFleetGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFleetGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetGroupsRow
	for rows.Next() {
		var i ListFleetGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Label,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFleetGroup = `-- name: UpdateFleetGroup :execrows
UPDATE fleet_groups
SET label       = $1,
    description = $2,
    updated_at  = $3
WHERE id = $4
`

type UpdateFleetGroupParams struct {
	Label       string
	Description string
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateFleetGroup(ctx context.Context, arg UpdateFleetGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFleetGroup,
		arg.Label,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertFleetGroup = `-- name: UpsertFleetGroup :exec
INSERT INTO fleet_groups (id, name, label, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE
SET name        = EXCLUDED.name,
    label       = EXCLUDED.label,
    description = EXCLUDED.description,
    created_at  = EXCLUDED.created_at,
    updated_at  = EXCLUDED.updated_at
`

type UpsertFleetGroupParams struct {
	ID          uuid.UUID
	Name        string
	Label       string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpsertFleetGroup(ctx context.Context, arg UpsertFleetGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertFleetGroup,
		arg.ID,
		arg.Name,
		arg.Label,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
