// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration_providers.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteIntegrationProvider = `-- name: DeleteIntegrationProvider :execrows
DELETE FROM integration_providers WHERE id = $1
`

func (q *Queries) DeleteIntegrationProvider(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIntegrationProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIntegrationProvider = `-- name: GetIntegrationProvider :one

SELECT id, kind, label, config, created_at, updated_at
FROM integration_providers
WHERE id = $1
`

// R-Q-03: integration_providers — operator-managed credential
// providers (api keys / webhooks for fleet group integrations).
func (q *Queries) GetIntegrationProvider(ctx context.Context, id uuid.UUID) (IntegrationProvider, error) {
	row := q.db.QueryRowContext(ctx, getIntegrationProvider, id)
	var i IntegrationProvider
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Label,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationProviders = `-- name: ListIntegrationProviders :many
SELECT id, kind, label, config, created_at, updated_at
FROM integration_providers
ORDER BY label, id
`

func (q *Queries) ListIntegrationProviders(ctx context.Context) ([]IntegrationProvider, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationProvider
	for rows.Next() {
		var i IntegrationProvider
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Label,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntegrationProvider = `-- name: UpsertIntegrationProvider :exec
INSERT INTO integration_providers (id, kind, label, config, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE
SET kind       = EXCLUDED.kind,
    label      = EXCLUDED.label,
    config     = EXCLUDED.config,
    updated_at = EXCLUDED.updated_at
`

type UpsertIntegrationProviderParams struct {
	ID        uuid.UUID
	Kind      string
	Label     string
	Config    json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertIntegrationProvider(ctx context.Context, arg UpsertIntegrationProviderParams) error {
	_, err := q.db.ExecContext(ctx, upsertIntegrationProvider,
		arg.ID,
		arg.Kind,
		arg.Label,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
