// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_targets.sql

package dbsqlc

import (
	"context"
)

const listJobTargets = `-- name: ListJobTargets :many
SELECT job_id, agent_id, status, result_text, result_json, updated_at
FROM job_targets
WHERE job_id = $1
ORDER BY agent_id
`

func (q *Queries) ListJobTargets(ctx context.Context, jobID string) ([]JobTarget, error) {
	rows, err := q.db.QueryContext(ctx, listJobTargets, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobTarget
	for rows.Next() {
		var i JobTarget
		if err := rows.Scan(
			&i.JobID,
			&i.AgentID,
			&i.Status,
			&i.ResultText,
			&i.ResultJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
