// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbsqlc

import (
	"context"
)

const listJobs = `-- name: ListJobs :many
SELECT id, action, idempotency_key, actor_id, status, created_at, ttl_nanos, payload_json
FROM jobs
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.IdempotencyKey,
			&i.ActorID,
			&i.Status,
			&i.CreatedAt,
			&i.TtlNanos,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
