// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbsqlc

import (
	"context"
	"time"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, action, idempotency_key, actor_id, status, created_at, ttl_nanos, payload_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateJobParams struct {
	ID             string
	Action         string
	IdempotencyKey string
	ActorID        string
	Status         string
	CreatedAt      time.Time
	TtlNanos       int64
	PayloadJson    string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.Action,
		arg.IdempotencyKey,
		arg.ActorID,
		arg.Status,
		arg.CreatedAt,
		arg.TtlNanos,
		arg.PayloadJson,
	)
	return err
}

const listJobs = `-- name: ListJobs :many
SELECT id, action, idempotency_key, actor_id, status, created_at, ttl_nanos, payload_json
FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.IdempotencyKey,
			&i.ActorID,
			&i.Status,
			&i.CreatedAt,
			&i.TtlNanos,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
