// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_lockouts.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteExpiredLoginLockouts = `-- name: DeleteExpiredLoginLockouts :execrows
DELETE FROM login_lockouts WHERE updated_at < $1
`

func (q *Queries) DeleteExpiredLoginLockouts(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredLoginLockouts, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLoginLockout = `-- name: DeleteLoginLockout :exec
DELETE FROM login_lockouts WHERE username = $1
`

func (q *Queries) DeleteLoginLockout(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteLoginLockout, username)
	return err
}

const getLoginLockout = `-- name: GetLoginLockout :one

SELECT username, failures, locked_at, updated_at
FROM login_lockouts
WHERE username = $1
`

// R-Q-03: login_lockouts — durable failure-count + lock state per
// username so a CP restart cannot silently reset the lockout window.
func (q *Queries) GetLoginLockout(ctx context.Context, username string) (LoginLockout, error) {
	row := q.db.QueryRowContext(ctx, getLoginLockout, username)
	var i LoginLockout
	err := row.Scan(
		&i.Username,
		&i.Failures,
		&i.LockedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLoginLockouts = `-- name: ListLoginLockouts :many
SELECT username, failures, locked_at, updated_at
FROM login_lockouts
`

func (q *Queries) ListLoginLockouts(ctx context.Context) ([]LoginLockout, error) {
	rows, err := q.db.QueryContext(ctx, listLoginLockouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoginLockout
	for rows.Next() {
		var i LoginLockout
		if err := rows.Scan(
			&i.Username,
			&i.Failures,
			&i.LockedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLoginLockout = `-- name: UpsertLoginLockout :exec
INSERT INTO login_lockouts (username, failures, locked_at, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (username) DO UPDATE SET
    failures = EXCLUDED.failures,
    locked_at = EXCLUDED.locked_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertLoginLockoutParams struct {
	Username  string
	Failures  int32
	LockedAt  sql.NullTime
	UpdatedAt time.Time
}

func (q *Queries) UpsertLoginLockout(ctx context.Context, arg UpsertLoginLockoutParams) error {
	_, err := q.db.ExecContext(ctx, upsertLoginLockout,
		arg.Username,
		arg.Failures,
		arg.LockedAt,
		arg.UpdatedAt,
	)
	return err
}
