// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metric_snapshots.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"
)

const appendMetricSnapshot = `-- name: AppendMetricSnapshot :exec
INSERT INTO metric_snapshots (id, agent_id, instance_id, captured_at, values)
VALUES ($1, $2, $3, $4, $5)
`

type AppendMetricSnapshotParams struct {
	ID         string
	AgentID    string
	InstanceID string
	CapturedAt time.Time
	Values     json.RawMessage
}

func (q *Queries) AppendMetricSnapshot(ctx context.Context, arg AppendMetricSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, appendMetricSnapshot,
		arg.ID,
		arg.AgentID,
		arg.InstanceID,
		arg.CapturedAt,
		arg.Values,
	)
	return err
}

const listMetricSnapshots = `-- name: ListMetricSnapshots :many

SELECT id, agent_id, instance_id, captured_at, values FROM (
  SELECT id, agent_id, instance_id, captured_at, values
  FROM metric_snapshots
  ORDER BY captured_at DESC, id DESC
  LIMIT 512
) capped
ORDER BY captured_at ASC, id ASC
`

// R-Q-03: metric_snapshots — historical agent metric blobs.
// M4: capped at 512 rows (keeping the newest 512, returned oldest→newest) to
// match the hand-written storage.Store implementations
// (internal/controlplane/storage/sqlite/metrics.go,
// internal/controlplane/storage/postgres/metrics.go) that actually serve
// this query at runtime. This sqlc-generated query is not currently wired
// into storage.Store, but it must not silently diverge from the documented
// 512-row contract (http_inventory.go) if it is ever used directly via
// Store.Queries().
func (q *Queries) ListMetricSnapshots(ctx context.Context) ([]MetricSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listMetricSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricSnapshot
	for rows.Next() {
		var i MetricSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.InstanceID,
			&i.CapturedAt,
			&i.Values,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneMetricSnapshots = `-- name: PruneMetricSnapshots :execrows
DELETE FROM metric_snapshots WHERE captured_at < $1
`

func (q *Queries) PruneMetricSnapshots(ctx context.Context, capturedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneMetricSnapshots, capturedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
