// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           string
	NodeName     string
	FleetGroupID pgtype.Text
	Version      string
	ReadOnly     bool
	LastSeenAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type AuditEvent struct {
	ID        string
	ActorID   string
	Action    string
	TargetID  string
	Details   []byte
	CreatedAt pgtype.Timestamptz
}

type CertificateAuthority struct {
	Scope         string
	CaPem         string
	PrivateKeyPem string
	UpdatedAt     pgtype.Timestamptz
}

type Client struct {
	ID                string
	Name              string
	SecretCiphertext  string
	UserAdTag         string
	Enabled           bool
	MaxTcpConns       int64
	MaxUniqueIps      int64
	DataQuotaBytes    int64
	ExpirationRfc3339 string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type ClientAssignment struct {
	ID           string
	ClientID     string
	TargetType   string
	FleetGroupID pgtype.Text
	AgentID      pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type ClientDeployment struct {
	ClientID         string
	AgentID          string
	DesiredOperation string
	Status           string
	LastError        string
	ConnectionLink   string
	LastAppliedAt    pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type EnrollmentToken struct {
	Value        string
	FleetGroupID pgtype.Text
	IssuedAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	ConsumedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

type FleetGroup struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Job struct {
	ID             string
	Action         string
	IdempotencyKey string
	ActorID        string
	Status         string
	CreatedAt      pgtype.Timestamptz
	TtlNanos       int64
	PayloadJson    string
}

type JobTarget struct {
	JobID      string
	AgentID    string
	Status     string
	ResultText string
	ResultJson string
	UpdatedAt  pgtype.Timestamptz
}

type MetricSnapshot struct {
	ID         string
	AgentID    string
	InstanceID string
	CapturedAt pgtype.Timestamptz
	Values     []byte
}

type PanelSetting struct {
	Scope              string
	HttpPublicUrl      string
	HttpRootPath       string
	GrpcPublicEndpoint string
	HttpListenAddress  string
	GrpcListenAddress  string
	TlsMode            string
	TlsCertFile        string
	TlsKeyFile         string
	UpdatedAt          pgtype.Timestamptz
}

type TelemtInstance struct {
	ID                string
	AgentID           string
	Name              string
	Version           string
	ConfigFingerprint string
	ConnectedUsers    int64
	ReadOnly          bool
	UpdatedAt         pgtype.Timestamptz
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	TotpEnabled  bool
	TotpSecret   string
	CreatedAt    pgtype.Timestamptz
}

type UserAppearance struct {
	UserID    string
	Theme     string
	Density   string
	UpdatedAt pgtype.Timestamptz
}
