// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: panel_settings.sql

package dbsqlc

import (
	"context"
	"time"
)

const getPanelSettings = `-- name: GetPanelSettings :one

SELECT http_public_url, grpc_public_endpoint, password_min_length, updated_at
FROM panel_settings
WHERE scope = $1
`

type GetPanelSettingsRow struct {
	HttpPublicUrl      string
	GrpcPublicEndpoint string
	PasswordMinLength  int32
	UpdatedAt          time.Time
}

// R-Q-03: panel_settings — operator-tunable HTTP/gRPC public URLs and security policy.
func (q *Queries) GetPanelSettings(ctx context.Context, scope string) (GetPanelSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getPanelSettings, scope)
	var i GetPanelSettingsRow
	err := row.Scan(
		&i.HttpPublicUrl,
		&i.GrpcPublicEndpoint,
		&i.PasswordMinLength,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPanelSettings = `-- name: UpsertPanelSettings :exec
INSERT INTO panel_settings (scope, http_public_url, grpc_public_endpoint, password_min_length, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scope) DO UPDATE
SET http_public_url = EXCLUDED.http_public_url,
    grpc_public_endpoint = EXCLUDED.grpc_public_endpoint,
    password_min_length = EXCLUDED.password_min_length,
    updated_at = EXCLUDED.updated_at
`

type UpsertPanelSettingsParams struct {
	Scope              string
	HttpPublicUrl      string
	GrpcPublicEndpoint string
	PasswordMinLength  int32
	UpdatedAt          time.Time
}

func (q *Queries) UpsertPanelSettings(ctx context.Context, arg UpsertPanelSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertPanelSettings,
		arg.Scope,
		arg.HttpPublicUrl,
		arg.GrpcPublicEndpoint,
		arg.PasswordMinLength,
		arg.UpdatedAt,
	)
	return err
}
