// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retention_settings.sql

package dbsqlc

import (
	"context"
	"time"
)

const getRetentionJSON = `-- name: GetRetentionJSON :one

SELECT retention_json FROM panel_settings WHERE scope = $1
`

// R-Q-03: retention settings ride alongside the panel_settings row in
// the retention_json column (added by migration 0009). These two
// queries are the read/write hot path used by GetRetentionSettings /
// PutRetentionSettings.
func (q *Queries) GetRetentionJSON(ctx context.Context, scope string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRetentionJSON, scope)
	var retention_json string
	err := row.Scan(&retention_json)
	return retention_json, err
}

const upsertRetentionJSON = `-- name: UpsertRetentionJSON :exec
INSERT INTO panel_settings (scope, http_public_url, grpc_public_endpoint, retention_json, updated_at)
VALUES ($1, '', '', $2, $3)
ON CONFLICT (scope) DO UPDATE
SET retention_json = EXCLUDED.retention_json,
    updated_at = EXCLUDED.updated_at
`

type UpsertRetentionJSONParams struct {
	Scope         string
	RetentionJson string
	UpdatedAt     time.Time
}

func (q *Queries) UpsertRetentionJSON(ctx context.Context, arg UpsertRetentionJSONParams) error {
	_, err := q.db.ExecContext(ctx, upsertRetentionJSON, arg.Scope, arg.RetentionJson, arg.UpdatedAt)
	return err
}
