// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime_settings.sql

package dbsqlc

import (
	"context"
)

const getRuntimeSetting = `-- name: GetRuntimeSetting :one

SELECT name, value_json, updated_at, updated_by
  FROM runtime_settings
 WHERE name = $1
`

// runtime_settings: operational settings without a dedicated typed
// column on panel_settings. Backing store for sub-project B fields.
func (q *Queries) GetRuntimeSetting(ctx context.Context, name string) (RuntimeSetting, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeSetting, name)
	var i RuntimeSetting
	err := row.Scan(
		&i.Name,
		&i.ValueJson,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertRuntimeSetting = `-- name: UpsertRuntimeSetting :exec
INSERT INTO runtime_settings (name, value_json, updated_at, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE
   SET value_json = EXCLUDED.value_json,
       updated_at = EXCLUDED.updated_at,
       updated_by = EXCLUDED.updated_by
`

type UpsertRuntimeSettingParams struct {
	Name      string
	ValueJson string
	UpdatedAt int64
	UpdatedBy string
}

func (q *Queries) UpsertRuntimeSetting(ctx context.Context, arg UpsertRuntimeSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertRuntimeSetting,
		arg.Name,
		arg.ValueJson,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}
