// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbsqlc

import (
	"context"
	"time"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE created_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, createdAt)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one

SELECT id, user_id, created_at, last_seen_at
FROM sessions
WHERE id = $1
`

// Q5.U-Q-03: sqlc widening — sessions table joins the agents/jobs/
// job_targets cluster the postgres backend already routes through
// dbsqlc. Bringing more tables under sqlc gives the postgres-side
// code path compile-time type safety on every column.
func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, created_at, last_seen_at
FROM sessions
ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
