// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemt_runtime.sql

package dbsqlc

import (
	"context"
	"time"
)

const deleteTelemetryDiagnosticsCurrent = `-- name: DeleteTelemetryDiagnosticsCurrent :exec
DELETE FROM telemt_diagnostics_current WHERE agent_id = $1
`

func (q *Queries) DeleteTelemetryDiagnosticsCurrent(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetryDiagnosticsCurrent, agentID)
	return err
}

const deleteTelemetryRuntimeCurrent = `-- name: DeleteTelemetryRuntimeCurrent :exec

DELETE FROM telemt_runtime_current WHERE agent_id = $1
`

// R-Q-03: telemt_runtime_current — minimal coverage so the table is
// represented in db/queries. The full ~30-column shape stays inline
// in internal/controlplane/storage/postgres/telemetry.go where the
// bulk write helpers manage replace-by-agent semantics.
func (q *Queries) DeleteTelemetryRuntimeCurrent(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetryRuntimeCurrent, agentID)
	return err
}

const deleteTelemetryRuntimeDCsForAgent = `-- name: DeleteTelemetryRuntimeDCsForAgent :exec
DELETE FROM telemt_runtime_dcs_current WHERE agent_id = $1
`

func (q *Queries) DeleteTelemetryRuntimeDCsForAgent(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetryRuntimeDCsForAgent, agentID)
	return err
}

const deleteTelemetryRuntimeEventsForAgent = `-- name: DeleteTelemetryRuntimeEventsForAgent :exec
DELETE FROM telemt_runtime_events WHERE agent_id = $1
`

func (q *Queries) DeleteTelemetryRuntimeEventsForAgent(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetryRuntimeEventsForAgent, agentID)
	return err
}

const deleteTelemetryRuntimeUpstreamsForAgent = `-- name: DeleteTelemetryRuntimeUpstreamsForAgent :exec
DELETE FROM telemt_runtime_upstreams_current WHERE agent_id = $1
`

func (q *Queries) DeleteTelemetryRuntimeUpstreamsForAgent(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetryRuntimeUpstreamsForAgent, agentID)
	return err
}

const deleteTelemetrySecurityInventoryCurrent = `-- name: DeleteTelemetrySecurityInventoryCurrent :exec
DELETE FROM telemt_security_inventory_current WHERE agent_id = $1
`

func (q *Queries) DeleteTelemetrySecurityInventoryCurrent(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetrySecurityInventoryCurrent, agentID)
	return err
}

const pruneTelemetryRuntimeEvents = `-- name: PruneTelemetryRuntimeEvents :execrows
DELETE FROM telemt_runtime_events WHERE observed_at < $1
`

func (q *Queries) PruneTelemetryRuntimeEvents(ctx context.Context, observedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneTelemetryRuntimeEvents, observedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
