// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemt_instances.sql

package dbsqlc

import (
	"context"
	"time"
)

const listInstances = `-- name: ListInstances :many

SELECT id, agent_id, name, version, config_fingerprint, connections, read_only, updated_at
FROM telemt_instances
ORDER BY updated_at ASC, id ASC
`

// R-Q-03: telemt_instances — per-agent runtime metadata that the
// panel restores at boot.
func (q *Queries) ListInstances(ctx context.Context) ([]TelemtInstance, error) {
	rows, err := q.db.QueryContext(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemtInstance
	for rows.Next() {
		var i TelemtInstance
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Version,
			&i.ConfigFingerprint,
			&i.Connections,
			&i.ReadOnly,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInstance = `-- name: UpsertInstance :exec
INSERT INTO telemt_instances (
    id, agent_id, name, version, config_fingerprint, connections, read_only, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET agent_id = EXCLUDED.agent_id,
    name = EXCLUDED.name,
    version = EXCLUDED.version,
    config_fingerprint = EXCLUDED.config_fingerprint,
    connections = EXCLUDED.connections,
    read_only = EXCLUDED.read_only,
    updated_at = EXCLUDED.updated_at
`

type UpsertInstanceParams struct {
	ID                string
	AgentID           string
	Name              string
	Version           string
	ConfigFingerprint string
	Connections       int64
	ReadOnly          bool
	UpdatedAt         time.Time
}

func (q *Queries) UpsertInstance(ctx context.Context, arg UpsertInstanceParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstance,
		arg.ID,
		arg.AgentID,
		arg.Name,
		arg.Version,
		arg.ConfigFingerprint,
		arg.Connections,
		arg.ReadOnly,
		arg.UpdatedAt,
	)
	return err
}
