// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timeseries.sql

package dbsqlc

import (
	"context"
	"time"
)

const pruneDCHealthPoints = `-- name: PruneDCHealthPoints :execrows
DELETE FROM ts_dc_health WHERE captured_at < $1
`

func (q *Queries) PruneDCHealthPoints(ctx context.Context, capturedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneDCHealthPoints, capturedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneServerLoadHourly = `-- name: PruneServerLoadHourly :execrows
DELETE FROM ts_server_load_hourly WHERE bucket_hour < $1
`

func (q *Queries) PruneServerLoadHourly(ctx context.Context, bucketHour time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneServerLoadHourly, bucketHour)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneServerLoadPoints = `-- name: PruneServerLoadPoints :execrows

DELETE FROM ts_server_load WHERE captured_at < $1
`

// R-Q-03: timeseries tables (ts_server_load, ts_server_load_hourly,
// ts_dc_health) — append-only metric history. Most operations are
// bulk-write driven; this file covers the prune-only contract that
// the retention worker calls. Detail-page chart reads stay in
// internal/controlplane/storage/postgres/timeseries.go since they
// have backend-specific filter shapes.
func (q *Queries) PruneServerLoadPoints(ctx context.Context, capturedAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneServerLoadPoints, capturedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
