// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transport.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const clearAgentBootstrapToken = `-- name: ClearAgentBootstrapToken :exec
UPDATE agents
SET bootstrap_state = 'active',
    bootstrap_token_hash = NULL,
    bootstrap_expires_at = NULL
WHERE id = $1
`

func (q *Queries) ClearAgentBootstrapToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearAgentBootstrapToken, id)
	return err
}

const consumeAgentBootstrapToken = `-- name: ConsumeAgentBootstrapToken :execrows
UPDATE agents
SET bootstrap_state = 'active'
WHERE id = $1 AND bootstrap_state = 'pending'
`

// Atomically claim a pending bootstrap token: flips the state out of
// 'pending' so only the first concurrent enrollment proceeds. The
// token hash/expiry are intentionally preserved so a sign failure can
// revert the claim (RevertAgentBootstrapConsumed) and let the operator
// retry. Returns the number of rows affected (1 = claimed, 0 = already
// consumed by a concurrent enrollment / replay within the TTL).
func (q *Queries) ConsumeAgentBootstrapToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeAgentBootstrapToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireAgentBootstrapToken = `-- name: ExpireAgentBootstrapToken :exec
UPDATE agents
SET bootstrap_state = 'expired',
    bootstrap_token_hash = NULL
WHERE id = $1
`

func (q *Queries) ExpireAgentBootstrapToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, expireAgentBootstrapToken, id)
	return err
}

const getAgentTransport = `-- name: GetAgentTransport :one
SELECT id, transport_mode, dial_address, bootstrap_state,
       bootstrap_token_hash, bootstrap_expires_at
FROM agents
WHERE id = $1
`

type GetAgentTransportRow struct {
	ID                 string
	TransportMode      string
	DialAddress        sql.NullString
	BootstrapState     string
	BootstrapTokenHash []byte
	BootstrapExpiresAt sql.NullTime
}

func (q *Queries) GetAgentTransport(ctx context.Context, id string) (GetAgentTransportRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentTransport, id)
	var i GetAgentTransportRow
	err := row.Scan(
		&i.ID,
		&i.TransportMode,
		&i.DialAddress,
		&i.BootstrapState,
		&i.BootstrapTokenHash,
		&i.BootstrapExpiresAt,
	)
	return i, err
}

const listAgentsByTransportMode = `-- name: ListAgentsByTransportMode :many
SELECT id, transport_mode, dial_address, bootstrap_state
FROM agents
WHERE transport_mode = $1
`

type ListAgentsByTransportModeRow struct {
	ID             string
	TransportMode  string
	DialAddress    sql.NullString
	BootstrapState string
}

func (q *Queries) ListAgentsByTransportMode(ctx context.Context, transportMode string) ([]ListAgentsByTransportModeRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByTransportMode, transportMode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsByTransportModeRow
	for rows.Next() {
		var i ListAgentsByTransportModeRow
		if err := rows.Scan(
			&i.ID,
			&i.TransportMode,
			&i.DialAddress,
			&i.BootstrapState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revertAgentBootstrapConsumed = `-- name: RevertAgentBootstrapConsumed :exec
UPDATE agents
SET bootstrap_state = 'pending'
WHERE id = $1 AND bootstrap_state = 'active' AND bootstrap_token_hash IS NOT NULL
`

// Roll a claimed-but-not-completed token back to 'pending' for retry.
// Guarded by bootstrap_token_hash IS NOT NULL so it only ever reverts a
// row still mid-enrollment (the token has not been cleared), never a
// fully-enrolled agent.
func (q *Queries) RevertAgentBootstrapConsumed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revertAgentBootstrapConsumed, id)
	return err
}

const setAgentBootstrapToken = `-- name: SetAgentBootstrapToken :exec
UPDATE agents
SET bootstrap_state = 'pending',
    bootstrap_token_hash = $2,
    bootstrap_expires_at = $3
WHERE id = $1
`

type SetAgentBootstrapTokenParams struct {
	ID                 string
	BootstrapTokenHash []byte
	BootstrapExpiresAt sql.NullTime
}

func (q *Queries) SetAgentBootstrapToken(ctx context.Context, arg SetAgentBootstrapTokenParams) error {
	_, err := q.db.ExecContext(ctx, setAgentBootstrapToken, arg.ID, arg.BootstrapTokenHash, arg.BootstrapExpiresAt)
	return err
}

const updateAgentTransportMode = `-- name: UpdateAgentTransportMode :exec
UPDATE agents
SET transport_mode = $2,
    dial_address = $3
WHERE id = $1
`

type UpdateAgentTransportModeParams struct {
	ID            string
	TransportMode string
	DialAddress   sql.NullString
}

func (q *Queries) UpdateAgentTransportMode(ctx context.Context, arg UpdateAgentTransportModeParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentTransportMode, arg.ID, arg.TransportMode, arg.DialAddress)
	return err
}
