// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_config.sql

package dbsqlc

import (
	"context"
)

const getUpdateConfig = `-- name: GetUpdateConfig :one

SELECT value FROM update_config WHERE key = $1
`

// R-Q-03: update_config — single-key/value table that stores update
// channel settings + the running update-checker state.
func (q *Queries) GetUpdateConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUpdateConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertUpdateConfig = `-- name: UpsertUpdateConfig :exec
INSERT INTO update_config (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type UpsertUpdateConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertUpdateConfig(ctx context.Context, arg UpsertUpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertUpdateConfig, arg.Key, arg.Value)
	return err
}
