// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_appearance.sql

package dbsqlc

import (
	"context"
	"time"
)

const getUserAppearance = `-- name: GetUserAppearance :one

SELECT user_id, theme, density, help_mode, updated_at
FROM user_appearance
WHERE user_id = $1
`

// R-Q-03: user_appearance — per-user theme/density/help-mode prefs.
func (q *Queries) GetUserAppearance(ctx context.Context, userID string) (UserAppearance, error) {
	row := q.db.QueryRowContext(ctx, getUserAppearance, userID)
	var i UserAppearance
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.Density,
		&i.HelpMode,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAppearances = `-- name: ListUserAppearances :many
SELECT user_id, theme, density, help_mode, updated_at
FROM user_appearance
ORDER BY user_id ASC
`

func (q *Queries) ListUserAppearances(ctx context.Context) ([]UserAppearance, error) {
	rows, err := q.db.QueryContext(ctx, listUserAppearances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAppearance
	for rows.Next() {
		var i UserAppearance
		if err := rows.Scan(
			&i.UserID,
			&i.Theme,
			&i.Density,
			&i.HelpMode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserAppearance = `-- name: UpsertUserAppearance :exec
INSERT INTO user_appearance (user_id, theme, density, help_mode, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET theme = EXCLUDED.theme,
    density = EXCLUDED.density,
    help_mode = EXCLUDED.help_mode,
    updated_at = EXCLUDED.updated_at
`

type UpsertUserAppearanceParams struct {
	UserID    string
	Theme     string
	Density   string
	HelpMode  string
	UpdatedAt time.Time
}

func (q *Queries) UpsertUserAppearance(ctx context.Context, arg UpsertUserAppearanceParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserAppearance,
		arg.UserID,
		arg.Theme,
		arg.Density,
		arg.HelpMode,
		arg.UpdatedAt,
	)
	return err
}
