// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_fleet_group_scopes.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearUserFleetGroupScopes = `-- name: ClearUserFleetGroupScopes :exec
DELETE FROM user_fleet_group_scopes WHERE user_id = $1
`

func (q *Queries) ClearUserFleetGroupScopes(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, clearUserFleetGroupScopes, userID)
	return err
}

const insertUserFleetGroupScope = `-- name: InsertUserFleetGroupScope :exec
INSERT INTO user_fleet_group_scopes (user_id, fleet_group_id, granted_at, granted_by)
VALUES ($1, $2, $3, $4)
`

type InsertUserFleetGroupScopeParams struct {
	UserID       string
	FleetGroupID uuid.UUID
	GrantedAt    time.Time
	GrantedBy    string
}

func (q *Queries) InsertUserFleetGroupScope(ctx context.Context, arg InsertUserFleetGroupScopeParams) error {
	_, err := q.db.ExecContext(ctx, insertUserFleetGroupScope,
		arg.UserID,
		arg.FleetGroupID,
		arg.GrantedAt,
		arg.GrantedBy,
	)
	return err
}

const listAllUserFleetGroupScopes = `-- name: ListAllUserFleetGroupScopes :many
SELECT user_id, fleet_group_id::text AS fleet_group_id, granted_at, granted_by
FROM user_fleet_group_scopes
ORDER BY user_id, fleet_group_id
`

type ListAllUserFleetGroupScopesRow struct {
	UserID       string
	FleetGroupID string
	GrantedAt    time.Time
	GrantedBy    string
}

func (q *Queries) ListAllUserFleetGroupScopes(ctx context.Context) ([]ListAllUserFleetGroupScopesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllUserFleetGroupScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUserFleetGroupScopesRow
	for rows.Next() {
		var i ListAllUserFleetGroupScopesRow
		if err := rows.Scan(
			&i.UserID,
			&i.FleetGroupID,
			&i.GrantedAt,
			&i.GrantedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFleetGroupScopes = `-- name: ListUserFleetGroupScopes :many

SELECT fleet_group_id::text AS fleet_group_id
FROM user_fleet_group_scopes
WHERE user_id = $1
ORDER BY fleet_group_id
`

// R-Q-03: user_fleet_group_scopes — per-user fleet-group scope
// mapping introduced by R-S-14. The list/insert/delete queries
// reflect the same semantics that the storage layer exposes.
func (q *Queries) ListUserFleetGroupScopes(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserFleetGroupScopes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fleet_group_id string
		if err := rows.Scan(&fleet_group_id); err != nil {
			return nil, err
		}
		items = append(items, fleet_group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
