package migrate

import (
	"context"
	"database/sql"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	sqlitebaseline "github.com/lost-coder/panvex/db/migrations/sqlite/baseline"
	sqlitestore "github.com/lost-coder/panvex/internal/controlplane/storage/sqlite"
	_ "modernc.org/sqlite"
)

// TestBaselineEquivalence_SQLite proves that the fast-path
// (applyBaselineIfFresh inside sqlite.MigrateContext) produces a
// schema bit-equivalent to the linear apply of every historical
// migration. The committed baseline_v1.sql is auto-generated by
// TestRegenerateSQLiteBaseline; this test catches the case where
// somebody hand-edits one apply path but not the other.
func TestBaselineEquivalence_SQLite(t *testing.T) {
	ctx := context.Background()

	// Path A — fast-path via the production MigrateContext. The store
	// uses the same code lifecycle real installs see (Open → MigrateContext).
	storeA, err := sqlitestore.Open(filepath.Join(t.TempDir(), "fast.db"))
	if err != nil {
		t.Fatalf("Open fast-path store: %v", err)
	}
	t.Cleanup(func() { _ = storeA.Close() })
	fastDB := storeA.DB()
	fastSchema, err := schemaFingerprint(ctx, fastDB)
	if err != nil {
		t.Fatalf("dump fast schema: %v", err)
	}

	// Path B — apply baseline_v1.sql directly to a virgin DB. This
	// must produce the same schema, since the file IS the consolidated
	// migration output the production code applies. Sanity check that
	// the embed.FS round-trips properly and the SQL is executable.
	baseSQL, err := sqlitebaseline.FS.ReadFile("baseline_v1.sql")
	if err != nil {
		t.Fatalf("read baseline: %v", err)
	}
	rawDB, err := sql.Open("sqlite", filepath.Join(t.TempDir(), "raw.db"))
	if err != nil {
		t.Fatalf("open raw db: %v", err)
	}
	t.Cleanup(func() { _ = rawDB.Close() })
	if _, err := rawDB.ExecContext(ctx, string(baseSQL)); err != nil {
		t.Fatalf("exec baseline: %v", err)
	}
	rawSchema, err := schemaFingerprint(ctx, rawDB)
	if err != nil {
		t.Fatalf("dump raw schema: %v", err)
	}
	if rawSchema != fastSchema {
		t.Errorf("schema drift between MigrateContext and raw baseline apply:\n"+
			" fast = %q\n raw  = %q", truncate(fastSchema, 400), truncate(rawSchema, 400))
	}

	// Cross-check: the active path is the fast one — confirm that.
	// On a fresh DB, applyBaselineIfFresh runs first; goose then sees
	// "everything up to v39 already applied" and walks zero further
	// migrations.
	gooseVer, err := readMaxGooseVersion(ctx, fastDB)
	if err != nil {
		t.Fatalf("read goose version: %v", err)
	}
	if gooseVer != int64(sqlitebaseline.LatestVersion) {
		t.Errorf("after fast-path MigrateContext, goose_db_version max = %d, want %d",
			gooseVer, sqlitebaseline.LatestVersion)
	}
}

// schemaFingerprint produces a deterministic representation of every
// schema object in the DB, modulo SQLite's internal sqlite_sequence
// table (which both paths create on-demand for AUTOINCREMENT rows
// and may diverge by timing).
func schemaFingerprint(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT type, name, COALESCE(sql, '')
		FROM sqlite_master
		WHERE name NOT LIKE 'sqlite_%'
		ORDER BY type, name
	`)
	if err != nil {
		return "", err
	}
	defer rows.Close()
	var lines []string
	for rows.Next() {
		var typeName, name, ddl string
		if err := rows.Scan(&typeName, &name, &ddl); err != nil {
			return "", err
		}
		lines = append(lines, typeName+"\x1f"+name+"\x1f"+strings.TrimSpace(ddl))
	}
	if err := rows.Err(); err != nil {
		return "", err
	}
	sort.Strings(lines)
	return strings.Join(lines, "\n"), nil
}

func readMaxGooseVersion(ctx context.Context, db *sql.DB) (int64, error) {
	var v int64
	if err := db.QueryRowContext(ctx,
		"SELECT COALESCE(MAX(version_id), 0) FROM goose_db_version WHERE is_applied = 1",
	).Scan(&v); err != nil {
		return 0, err
	}
	return v, nil
}
