package migrate

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	sqlitemigrations "github.com/lost-coder/panvex/db/migrations/sqlite"
	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite"
)

// regenBaseline toggles overwriting the committed
// db/migrations/sqlite/baseline_v1.sql with whatever sqlite_master
// returns after applying every historical migration. Operators run
// this whenever migrations are added or removed; on a normal `go test`
// run we still execute the dump and compare against the committed
// file so a missed update fails CI.
var regenBaseline = flag.Bool("regen-baseline", false, "rewrite db/migrations/sqlite/baseline_v1.sql from current migrations")

// TestRegenerateSQLiteBaseline produces baseline_v1.sql by replaying
// the embedded migrations against a fresh in-memory SQLite database.
// Without -regen-baseline it compares the produced SQL to the
// committed file; with the flag it overwrites the file. The intent is
// that operators editing migrations run this test once, commit the
// regenerated baseline, and CI then re-runs it in compare mode to
// catch stale baselines on subsequent PRs.
func TestRegenerateSQLiteBaseline(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	dbPath := filepath.Join(dir, "regen.db")
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("sql.Open: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	if _, err := db.ExecContext(ctx, "PRAGMA foreign_keys = ON"); err != nil {
		t.Fatalf("enable FK: %v", err)
	}

	// Run every migration via goose, then dump.
	goose.SetBaseFS(sqlitemigrations.FS)
	if err := goose.SetDialect("sqlite3"); err != nil {
		t.Fatalf("set dialect: %v", err)
	}
	if err := goose.UpContext(ctx, db, "."); err != nil {
		t.Fatalf("goose up: %v", err)
	}

	dump, err := dumpSQLiteSchema(ctx, db)
	if err != nil {
		t.Fatalf("dump schema: %v", err)
	}

	baselinePath := filepath.Join(repoRootForTest(t), "db", "migrations", "sqlite", "baseline", "baseline_v1.sql")
	if err := os.MkdirAll(filepath.Dir(baselinePath), 0o755); err != nil {
		t.Fatalf("mkdir baseline dir: %v", err)
	}

	if *regenBaseline {
		if err := os.WriteFile(baselinePath, []byte(dump), 0o644); err != nil {
			t.Fatalf("write baseline: %v", err)
		}
		t.Logf("rewrote %s (%d bytes)", baselinePath, len(dump))
		return
	}

	committed, err := os.ReadFile(baselinePath)
	if err != nil {
		// First-time generation: write the file and pass. Tests on
		// subsequent runs will fail-on-diff if migrations changed
		// without a baseline refresh.
		if !os.IsNotExist(err) {
			t.Fatalf("read baseline: %v", err)
		}
		if err := os.WriteFile(baselinePath, []byte(dump), 0o644); err != nil {
			t.Fatalf("write first-time baseline: %v", err)
		}
		t.Logf("first-time wrote %s (%d bytes)", baselinePath, len(dump))
		return
	}
	if string(committed) != dump {
		t.Fatalf("baseline drift: db/migrations/sqlite/baseline/baseline_v1.sql is out of sync with current migrations.\n"+
			"Re-run with -regen-baseline:\n"+
			"  go test -run TestRegenerateSQLiteBaseline -regen-baseline ./internal/controlplane/storage/migrate/...\n"+
			"diff (first 200 chars committed vs got):\n  committed: %q\n  got:       %q",
			truncate(string(committed), 200), truncate(dump, 200))
	}
}

// dumpSQLiteSchema produces a deterministic CREATE-statement dump of
// every persistent schema object plus the goose_db_version table data
// rows so the baseline can be applied to a fresh DB and the
// subsequent goose.Up call sees "everything 1..N already applied".
func dumpSQLiteSchema(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT type, name, sql
		FROM sqlite_master
		WHERE sql IS NOT NULL
		  AND name NOT LIKE 'sqlite_%'
		ORDER BY
			CASE type WHEN 'table' THEN 0
			          WHEN 'index' THEN 1
			          WHEN 'view'  THEN 2
			          WHEN 'trigger' THEN 3
			          ELSE 4 END,
			name
	`)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	var (
		statements []string
		preface    = "-- baseline_v1.sql (SQLite) — autogenerated by migrate.TestRegenerateSQLiteBaseline.\n" +
			"-- DO NOT EDIT BY HAND. Re-run the test with -regen-baseline to update.\n" +
			"-- See docs/superpowers/plans/2026-05-09-baseline-migration.md\n\n"
	)
	for rows.Next() {
		var typeName, name, ddl string
		if err := rows.Scan(&typeName, &name, &ddl); err != nil {
			return "", err
		}
		// SQLite stores the original CREATE without trailing semicolon;
		// add one for portable execution.
		statements = append(statements, strings.TrimRight(ddl, " \t\n;")+";")
	}
	if err := rows.Err(); err != nil {
		return "", err
	}

	// Append the goose_db_version rows so a fresh apply marks every
	// historical migration as already-run. The columns are (id,
	// version_id, is_applied, tstamp). We INSERT version_id only +
	// is_applied=1; id and tstamp default to AUTOINCREMENT / NOW.
	versions, err := dumpSQLiteGooseVersions(ctx, db)
	if err != nil {
		return "", err
	}
	statements = append(statements, versions)

	return preface + strings.Join(statements, "\n\n") + "\n", nil
}

func dumpSQLiteGooseVersions(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT version_id FROM goose_db_version WHERE is_applied = 1 ORDER BY version_id`)
	if err != nil {
		return "", err
	}
	defer rows.Close()
	var ids []int64
	for rows.Next() {
		var v int64
		if err := rows.Scan(&v); err != nil {
			return "", err
		}
		ids = append(ids, v)
	}
	if err := rows.Err(); err != nil {
		return "", err
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	if len(ids) == 0 {
		return "", nil
	}
	var b strings.Builder
	b.WriteString("-- Mark every historical migration as already applied so goose.Up sees a no-op.\n")
	b.WriteString("INSERT INTO goose_db_version (version_id, is_applied) VALUES\n")
	for i, v := range ids {
		if i > 0 {
			b.WriteString(",\n")
		}
		fmt.Fprintf(&b, "  (%d, 1)", v)
	}
	b.WriteString(";")
	return b.String(), nil
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// repoRootForTest walks up from the test working directory until it
// finds go.mod. Tests run with cwd = the package dir, so this lets
// us reach into db/migrations/ without hard-coding a path.
func repoRootForTest(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("could not find go.mod walking up from cwd")
		}
		dir = parent
	}
}
