package migrate_test

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/lost-coder/panvex/internal/controlplane/storage/postgres"
	"github.com/lost-coder/panvex/internal/controlplane/storage/sqlite"
)

// TestSchemaSyncPostgresMatchesSQLite (C9, H6) asserts that the
// PostgreSQL and SQLite migration bundles converge on the same schema:
// tables, column names, column data types (modulo a reviewed
// cross-engine allowlist), column nullability, CHECK constraint
// expressions, FK delete-rules, and index column-sets/uniqueness. The
// band-aid migration 0011_column_drift.sql exists precisely because the
// two bundles silently drifted once — without a CI guardrail that only
// gets caught in production. This test closes the loop by comparing the
// post-migration schemas side by side.
//
// Coverage:
//   - column NAMES, normalized via normalizeColumnNames (folds the
//     `_unix` / `_at` timestamp-convention suffixes) so paired columns
//     line up before any other comparison runs.
//   - column DATA TYPES: identical (case-insensitive) or present in
//     acceptedTypePairs, a hand-reviewed allowlist of legitimate
//     cross-engine type differences (see the table's inline comments).
//     Anything else fails naming both sides' actual type strings.
//   - column NULLABILITY: SQLite's pragma_table_info `notnull` flag vs
//     PostgreSQL's `is_nullable`, compared after name normalization.
//   - CHECK constraint expressions (normalized, C1) and FK delete-rules,
//     as before.
//   - INDEX column-sets and uniqueness per table: PK-backing and
//     engine-autogenerated indexes are compared by (sorted column-set,
//     uniqueness) rather than by name, since names are not portable
//     across engines (e.g. `sqlite_autoindex_foo_1` vs `foo_pkey`).
//
// Limitations:
//   - column DEFAULT values are captured best-effort for diagnostics but
//     not asserted for equality — default *rendering* legitimately
//     differs per engine (e.g. `CURRENT_TIMESTAMP` vs `NOW()`,
//     `'{}'::jsonb` vs `'{}'`) even when the semantic default is the
//     same, so byte-for-byte comparison would be noise rather than
//     signal.
//   - index WHERE-clauses (partial indexes) are not compared textually,
//     only that both sides have a partial index over the same columns;
//     dialect-specific partial-predicate syntax makes textual comparison
//     as noisy as defaults.
//   - goose_db_version is the bookkeeping table goose maintains; we
//     ignore it.
//
// Requires a live PostgreSQL instance reachable via
// PANVEX_POSTGRES_TEST_DSN. The DSN must point at a throwaway DB —
// the test drops and recreates the `public` schema.
func TestSchemaSyncPostgresMatchesSQLite(t *testing.T) {
	dsn := os.Getenv("PANVEX_POSTGRES_TEST_DSN")
	if dsn == "" {
		t.Skip("PANVEX_POSTGRES_TEST_DSN is not set")
	}

	pg, err := postgres.Open(dsn)
	if err != nil {
		t.Fatalf("postgres.Open: %v", err)
	}
	defer pg.Close()

	rawPg, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("sql.Open pgx: %v", err)
	}
	defer rawPg.Close()

	// Nuke and rebuild public schema so the run is hermetic.
	if _, err := rawPg.ExecContext(context.Background(),
		"DROP SCHEMA public CASCADE; CREATE SCHEMA public;"); err != nil {
		t.Fatalf("reset public schema: %v", err)
	}
	if err := postgres.Migrate(rawPg); err != nil {
		t.Fatalf("postgres.Migrate: %v", err)
	}

	dbPath := filepath.Join(t.TempDir(), "schema_sync.db")
	sq, err := sqlite.Open(dbPath)
	if err != nil {
		t.Fatalf("sqlite.Open: %v", err)
	}
	defer sq.Close()

	// sqlite.Open applies migrations internally.

	sqliteSchema, err := readSQLiteSchema(t.Context(), dbPath)
	if err != nil {
		t.Fatalf("read sqlite schema: %v", err)
	}
	pgSchema, err := readPostgresSchema(t.Context(), rawPg)
	if err != nil {
		t.Fatalf("read postgres schema: %v", err)
	}

	assertSchemasMatch(t, pgSchema, sqliteSchema)
}

type tableSchema struct {
	columns []string
	// colInfo maps (normalized) column name -> type/nullability detail,
	// keyed the same way columns are normalized for comparison.
	colInfo map[string]columnInfo
	// checks holds normalized CHECK constraint expressions (see
	// normalizeCheckExpr) so enum-guard drift between the dialects is
	// caught in CI, not in production (C1).
	checks []string
	// fks holds normalized "column->ref_table [DELETE_RULE]" strings so
	// a missing ON DELETE CASCADE in one dialect fails the test.
	fks []string
	// indexes holds one entry per index/unique-constraint on the table.
	indexes []indexInfo
}

// columnInfo captures the per-column detail needed for cross-engine
// type/nullability comparison. rawName preserves the pre-normalization
// column name for error messages.
type columnInfo struct {
	rawName  string
	dataType string
	nullable bool
	// defaultVal is best-effort and only surfaced in diagnostics — see
	// the "Limitations" doc comment on why defaults are not asserted.
	defaultVal string
}

// indexInfo describes one index/unique-constraint as a normalized,
// order-independent column-set plus its uniqueness flag. Index NAMES
// are intentionally not part of the comparison key: they are not
// portable across engines (sqlite_autoindex_foo_1 vs foo_pkey).
type indexInfo struct {
	columns  []string
	isUnique bool
	isPK     bool
	partial  bool
}

// acceptedTypePairs allowlists cross-engine column type pairs that are
// deliberate, reviewed, and semantically equivalent (case-insensitive,
// order-independent — see typePairKey). Every entry below was verified
// by reading both dialects' migrations for at least one real column
// pair; do not add an entry without doing the same.
var acceptedTypePairs = map[[2]string]bool{
	// SQLite has no native 64-bit-only integer distinct from its
	// generic INTEGER affinity (which stores up to 8 bytes); PostgreSQL
	// uses BIGINT/BIGSERIAL for counters, byte totals, and sequence ids
	// (db/migrations/postgres/0001_init.sql connected_users,
	// 0041_enrollment_attempts.sql id BIGSERIAL) while the SQLite side
	// declares them INTEGER (0001_init.sql, 0041_enrollment_attempts.sql
	// id INTEGER PRIMARY KEY AUTOINCREMENT). Same value range in
	// practice; SQLite's type affinity system does not distinguish.
	typePairKey("bigint", "integer"): true,
	// SQLite has no BOOLEAN type; boolean columns are declared INTEGER
	// with a CHECK(col IN (0,1)) guard (e.g. agents.read_only in
	// sqlite/0001_init.sql vs BOOLEAN in postgres/0001_init.sql). The
	// CHECK itself is excluded from parity by isEngineInherentCheck.
	typePairKey("boolean", "integer"): true,
	// 0024_unify_real_to_double.sql promoted ts_server_load's float
	// columns to DOUBLE PRECISION on PostgreSQL to match SQLite's REAL
	// (which is always 8-byte/double-precision), explicitly to close a
	// precision gap — SQLite's REAL and PG's DOUBLE PRECISION are the
	// intended matching pair for those columns.
	typePairKey("double precision", "real"): true,
	// TIMESTAMPTZ (PG) vs INTEGER unix-seconds (SQLite `_unix` suffix
	// columns, e.g. agents.last_seen_at / last_seen_at_unix) is the
	// project's standard timestamp convention, documented in
	// sqlite/0001_init.sql and normalizeColumnNames above.
	typePairKey("timestamp with time zone", "integer"): true,
	// TIMESTAMPTZ (PG) vs TIMESTAMP (SQLite) is used for columns that
	// keep the `_at`/`ts` naming without a `_unix` counterpart, e.g.
	// webhook_outbox.created_at (postgres/0039 TIMESTAMPTZ DEFAULT
	// NOW() vs sqlite/0039 TIMESTAMP DEFAULT CURRENT_TIMESTAMP) and
	// enrollment_events.ts (postgres/0041 TIMESTAMPTZ vs sqlite/0041
	// TIMESTAMP). SQLite has no timezone-aware type; the store layer
	// normalizes both to Go time.Time (see 0049_agent_config_targets.sql
	// header comment).
	typePairKey("timestamp with time zone", "timestamp"): true,
	// SQLite has no JSONB type. jobs/audit_events/etc. JSON-shaped
	// columns are TEXT with a json_valid(...) CHECK guard added by
	// 0052_json_valid_checks.sql (M3) as the compensating control for
	// what PostgreSQL's JSONB type enforces at write time (e.g.
	// audit_events.details JSONB vs sqlite TEXT + CHECK). The json_valid
	// CHECKs are engine-inherent and excluded from CHECK parity by
	// isEngineInherentCheck, so this pair covers the type side.
	//
	// integration_providers.config used to be one of the columns relying
	// on this pair (PG JSONB vs SQLite TEXT+json_valid CHECK) until
	// bug1/H-6 (db/migrations/postgres/0052_integration_providers_config_text.sql)
	// converted PostgreSQL's side to TEXT too — that column is now
	// text/text on both engines and no longer needs this allowlist entry.
	// The entry itself stays: audit_events.details, metric_snapshots.values,
	// webhook_outbox.payload, and enrollment_events.fields_json are all
	// still JSONB on PostgreSQL / TEXT+CHECK on SQLite (verified against
	// db/migrations/postgres/0001_init.sql, 0039_webhook_outbox.sql,
	// 0041_enrollment_attempts.sql — none of those were touched by 0052).
	typePairKey("jsonb", "text"): true,
	// SQLite has no UUID type; fleet_groups.id and dependent FK columns
	// are UUID on PostgreSQL (postgres/0014_fleet_groups_redesign.sql)
	// but TEXT on SQLite, with UUID format enforced at the application
	// layer (see the 0014 sqlite migration header note).
	typePairKey("uuid", "text"): true,
	// agents.bootstrap_token_hash is BYTEA on PostgreSQL
	// (postgres/0030_node_transport_mode.sql) and BLOB on SQLite
	// (sqlite/0030_node_transport_mode.sql / 0050_check_parity.sql
	// table rebuild) — both dialects' native binary-blob type.
	typePairKey("bytea", "blob"): true,
}

// typePairKey normalizes a pair of type strings (lower-case, order
// independent) into the map key used by acceptedTypePairs.
func typePairKey(a, b string) [2]string {
	a, b = strings.ToLower(a), strings.ToLower(b)
	if a > b {
		a, b = b, a
	}
	return [2]string{a, b}
}

// typesMatch reports whether two column type strings are either
// identical (case-insensitive) or a reviewed cross-engine pair.
func typesMatch(a, b string) bool {
	if strings.EqualFold(a, b) {
		return true
	}
	return acceptedTypePairs[typePairKey(a, b)]
}

func assertSchemasMatch(t *testing.T, pg, sq map[string]tableSchema) {
	t.Helper()

	pgNames := sortedKeys(pg)
	sqNames := sortedKeys(sq)

	if !equalStringSlices(pgNames, sqNames) {
		onlyPG := diffSlices(pgNames, sqNames)
		onlySQ := diffSlices(sqNames, pgNames)
		if len(onlyPG) > 0 {
			t.Errorf("tables only in PostgreSQL: %v", onlyPG)
		}
		if len(onlySQ) > 0 {
			t.Errorf("tables only in SQLite: %v", onlySQ)
		}
	}

	for name := range pg {
		sqTbl, ok := sq[name]
		if !ok {
			continue
		}
		// Normalize timestamp-convention suffixes before comparing: SQLite
		// stores timestamps as INTEGER unix seconds with a `*_unix` suffix,
		// PostgreSQL stores them as TIMESTAMPTZ in columns named `*_at` /
		// `*_seen`. Both conventions describe the same logical field, so
		// stripping the suffix lets the test focus on structural drift
		// (missing columns, renamed prefixes) instead of the by-design
		// naming difference.
		pgCols := normalizeColumnNames(pg[name].columns)
		sqCols := normalizeColumnNames(sqTbl.columns)
		sort.Strings(pgCols)
		sort.Strings(sqCols)
		if !equalStringSlices(pgCols, sqCols) {
			onlyPG := diffSlices(pgCols, sqCols)
			onlySQ := diffSlices(sqCols, pgCols)
			if len(onlyPG) > 0 {
				t.Errorf("table %s: columns only in PostgreSQL: %v", name, onlyPG)
			}
			if len(onlySQ) > 0 {
				t.Errorf("table %s: columns only in SQLite: %v", name, onlySQ)
			}
		}
		assertStringSetMatch(t, name, "CHECK constraints", pg[name].checks, sqTbl.checks)
		assertStringSetMatch(t, name, "FK delete rules", pg[name].fks, sqTbl.fks)
		assertColumnTypesMatch(t, name, pg[name], sqTbl)
		assertIndexesMatch(t, name, pg[name].indexes, sqTbl.indexes)
	}
}

// assertColumnTypesMatch compares, per normalized column name, the data
// type (via typesMatch) and nullability between the two engines.
func assertColumnTypesMatch(t *testing.T, table string, pg, sq tableSchema) {
	t.Helper()
	for normName, pgCol := range pg.colInfo {
		sqCol, ok := sq.colInfo[normName]
		if !ok {
			// Missing-column drift is already reported by the caller's
			// column-name comparison; avoid double-reporting here.
			continue
		}
		if !typesMatch(pgCol.dataType, sqCol.dataType) {
			t.Errorf("table %s: column %s/%s type mismatch: postgres=%q sqlite=%q (not identical and not in acceptedTypePairs)",
				table, pgCol.rawName, sqCol.rawName, pgCol.dataType, sqCol.dataType)
		}
		if pgCol.nullable != sqCol.nullable {
			t.Errorf("table %s: column %s/%s nullability mismatch: postgres nullable=%v sqlite nullable=%v",
				table, pgCol.rawName, sqCol.rawName, pgCol.nullable, sqCol.nullable)
		}
	}
}

// assertIndexesMatch compares index column-sets (order-independent,
// name-normalized) and uniqueness between the two engines. Index NAMES
// are not compared — they are not portable across dialects.
func assertIndexesMatch(t *testing.T, table string, pg, sq []indexInfo) {
	t.Helper()
	pgSet := indexSignatureSet(pg)
	sqSet := indexSignatureSet(sq)

	var pgSigs, sqSigs []string
	for sig := range pgSet {
		pgSigs = append(pgSigs, sig)
	}
	for sig := range sqSet {
		sqSigs = append(sqSigs, sig)
	}
	sort.Strings(pgSigs)
	sort.Strings(sqSigs)

	if only := diffSlices(pgSigs, sqSigs); len(only) > 0 {
		t.Errorf("table %s: indexes only in PostgreSQL (columns[unique]): %v", table, only)
	}
	if only := diffSlices(sqSigs, pgSigs); len(only) > 0 {
		t.Errorf("table %s: indexes only in SQLite (columns[unique]): %v", table, only)
	}
}

// indexSignatureSet renders each index as "col1,col2[unique]" or
// "col1,col2[nonunique]", using normalized + sorted column names so
// index order and naming conventions never cause a spurious mismatch.
// Multiple indexes that collapse to the same signature (e.g. a PK's
// implicit unique index and an explicit UNIQUE constraint on the same
// columns) are deduplicated, since both engines only need to agree that
// *some* index enforces that column-set/uniqueness combination.
//
// The partial-index flag is deliberately NOT part of the signature.
// clients.subscription_token is the concrete example: PostgreSQL
// declares `CREATE UNIQUE INDEX ... WHERE subscription_token IS NOT
// NULL` (postgres/0051) because Postgres UNIQUE indexes treat every NULL
// as a distinct, non-conflicting value only when a partial predicate
// excludes NULLs from a *plain* UNIQUE constraint — but SQLite's UNIQUE
// index ALREADY treats NULLs as pairwise-distinct by default (documented
// in sqlite/0051), so the SQLite side omits the predicate entirely and
// still enforces the identical semantic: "non-NULL tokens must be
// unique, any number of NULLs allowed". Comparing the WHERE-clause
// presence textually would flag this correct-by-construction difference
// as a bug.
func indexSignatureSet(idxs []indexInfo) map[string]bool {
	out := map[string]bool{}
	for _, idx := range idxs {
		cols := normalizeColumnNames(idx.columns)
		sort.Strings(cols)
		sig := strings.Join(cols, ",")
		if idx.isUnique {
			sig += "[unique]"
		} else {
			sig += "[nonunique]"
		}
		out[sig] = true
	}
	return out
}

// assertStringSetMatch compares two unordered normalized-string sets and
// reports per-side differences with table context.
func assertStringSetMatch(t *testing.T, table, kind string, pgSet, sqSet []string) {
	t.Helper()
	pgSorted := append([]string(nil), pgSet...)
	sqSorted := append([]string(nil), sqSet...)
	sort.Strings(pgSorted)
	sort.Strings(sqSorted)
	if equalStringSlices(pgSorted, sqSorted) {
		return
	}
	if only := diffSlices(pgSorted, sqSorted); len(only) > 0 {
		t.Errorf("table %s: %s only in PostgreSQL: %v", table, kind, only)
	}
	if only := diffSlices(sqSorted, pgSorted); len(only) > 0 {
		t.Errorf("table %s: %s only in SQLite: %v", table, kind, only)
	}
}

// normalizeColumnNames folds the PG/SQLite timestamp-column conventions to a
// single form. Strip a trailing `_unix` (SQLite INTEGER unix seconds) or
// `_at` (PostgreSQL TIMESTAMPTZ) so pairs like
// `created_at` / `created_at_unix` collapse to `created`, and
// `timestamp_at` / `timestamp_unix` collapse to `timestamp`.
func normalizeColumnNames(cols []string) []string {
	out := make([]string, 0, len(cols))
	for _, c := range cols {
		out = append(out, normalizeColumnName(c))
	}
	return out
}

// normalizeColumnName applies the single-column form of the
// `_unix`/`_at` suffix fold used throughout this file (column-set
// comparison, colInfo map keys, FK column names).
func normalizeColumnName(c string) string {
	c = strings.TrimSuffix(c, "_unix")
	c = strings.TrimSuffix(c, "_at")
	return c
}

func readPostgresSchema(ctx context.Context, db *sql.DB) (map[string]tableSchema, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT table_name, column_name, data_type, is_nullable, column_default
		FROM information_schema.columns
		WHERE table_schema = 'public'
		  AND table_name <> 'goose_db_version'
		ORDER BY table_name, ordinal_position
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	result := map[string]tableSchema{}
	for rows.Next() {
		var table, column, dataType, isNullable string
		var colDefault sql.NullString
		if err := rows.Scan(&table, &column, &dataType, &isNullable, &colDefault); err != nil {
			return nil, err
		}
		ts := result[table]
		ts.columns = append(ts.columns, column)
		if ts.colInfo == nil {
			ts.colInfo = map[string]columnInfo{}
		}
		ts.colInfo[normalizeColumnName(column)] = columnInfo{
			rawName:    column,
			dataType:   dataType,
			nullable:   strings.EqualFold(isNullable, "YES"),
			defaultVal: colDefault.String,
		}
		result[table] = ts
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	idxRows, err := db.QueryContext(ctx, `
		SELECT t.relname AS table_name, ix.indisunique, i.indexrelid IN (SELECT indexrelid FROM pg_index WHERE indisprimary) AS is_pk,
		       ix.indpred IS NOT NULL AS is_partial,
		       array_to_string(array_agg(a.attname ORDER BY x.n), ',') AS cols
		FROM pg_index ix
		JOIN pg_index i ON i.indexrelid = ix.indexrelid
		JOIN pg_class t ON t.oid = ix.indrelid
		JOIN pg_namespace n ON n.oid = t.relnamespace
		JOIN unnest(ix.indkey) WITH ORDINALITY AS x(attnum, n) ON true
		JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = x.attnum
		WHERE n.nspname = 'public' AND t.relname <> 'goose_db_version'
		GROUP BY t.relname, ix.indexrelid, ix.indisunique, ix.indpred, i.indexrelid
	`)
	if err != nil {
		return nil, err
	}
	defer idxRows.Close()
	for idxRows.Next() {
		var table, colList string
		var isUnique, isPK, isPartial bool
		if err := idxRows.Scan(&table, &isUnique, &isPK, &isPartial, &colList); err != nil {
			return nil, err
		}
		ts := result[table]
		ts.indexes = append(ts.indexes, indexInfo{
			columns:  strings.Split(colList, ","),
			isUnique: isUnique,
			isPK:     isPK,
			partial:  isPartial,
		})
		result[table] = ts
	}
	if err := idxRows.Err(); err != nil {
		return nil, err
	}

	checkRows, err := db.QueryContext(ctx, `
		SELECT rel.relname, pg_get_constraintdef(con.oid)
		FROM pg_constraint con
		JOIN pg_class rel ON rel.oid = con.conrelid
		JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
		WHERE nsp.nspname = 'public' AND con.contype = 'c'
	`)
	if err != nil {
		return nil, err
	}
	defer checkRows.Close()
	for checkRows.Next() {
		var table, def string
		if err := checkRows.Scan(&table, &def); err != nil {
			return nil, err
		}
		norm := normalizeCheckExpr(def)
		// Symmetric with readSQLiteSchema's filtering below: an
		// engine-inherent compensating control (e.g. the PVS-sealed JSON
		// CHECK, bug1/H-6) has no counterpart CHECK on the other engine by
		// design, so it must be excluded here too or it would show up as
		// "CHECK constraints only in PostgreSQL".
		if isEngineInherentCheck(norm) {
			continue
		}
		ts := result[table]
		ts.checks = append(ts.checks, norm)
		result[table] = ts
	}
	if err := checkRows.Err(); err != nil {
		return nil, err
	}

	fkRows, err := db.QueryContext(ctx, `
		SELECT tc.table_name, kcu.column_name, ccu.table_name AS foreign_table, rc.delete_rule
		FROM information_schema.table_constraints tc
		JOIN information_schema.key_column_usage kcu
		  ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema
		JOIN information_schema.referential_constraints rc
		  ON rc.constraint_name = tc.constraint_name AND rc.constraint_schema = tc.table_schema
		JOIN information_schema.constraint_column_usage ccu
		  ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
		WHERE tc.table_schema = 'public' AND tc.constraint_type = 'FOREIGN KEY'
	`)
	if err != nil {
		return nil, err
	}
	defer fkRows.Close()
	for fkRows.Next() {
		var table, column, refTable, rule string
		if err := fkRows.Scan(&table, &column, &refTable, &rule); err != nil {
			return nil, err
		}
		ts := result[table]
		ts.fks = append(ts.fks, normalizeFK(column, refTable, rule))
		result[table] = ts
	}
	if err := fkRows.Err(); err != nil {
		return nil, err
	}

	return result, nil
}

func readSQLiteSchema(ctx context.Context, path string) (map[string]tableSchema, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	defer db.Close()

	rows, err := db.QueryContext(ctx, `
		SELECT name FROM sqlite_master
		WHERE type = 'table'
		  AND name <> 'goose_db_version'
		  AND name NOT LIKE 'sqlite_%'
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	tables := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		tables = append(tables, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	result := map[string]tableSchema{}
	for _, name := range tables {
		cols, colInfo, err := readSQLiteTableColumns(ctx, db, name)
		if err != nil {
			return nil, err
		}

		var createSQL string
		if err := db.QueryRowContext(ctx,
			"SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", name).Scan(&createSQL); err != nil {
			return nil, err
		}
		var checks []string
		for _, expr := range extractSQLiteCheckExprs(createSQL) {
			norm := normalizeCheckExpr(expr)
			if isEngineInherentCheck(norm) {
				continue
			}
			checks = append(checks, norm)
		}

		fks, err := readSQLiteForeignKeys(ctx, db, name)
		if err != nil {
			return nil, err
		}
		idxs, err := readSQLiteIndexes(ctx, db, name)
		if err != nil {
			return nil, err
		}
		result[name] = tableSchema{columns: cols, colInfo: colInfo, checks: checks, fks: fks, indexes: idxs}
	}
	return result, nil
}

// readSQLiteForeignKeys lists normalized FK descriptors for one table.
func readSQLiteForeignKeys(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	rows, err := db.QueryContext(ctx,
		`SELECT "table", "from", on_delete FROM pragma_foreign_key_list(?)`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var refTable, from, rule string
		if err := rows.Scan(&refTable, &from, &rule); err != nil {
			return nil, err
		}
		out = append(out, normalizeFK(from, refTable, rule))
	}
	return out, rows.Err()
}

func sortedKeys(m map[string]tableSchema) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func equalStringSlices(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// readSQLiteTableColumns lists the columns of a single table plus their
// type/nullability/default, keyed by normalized column name for
// cross-engine comparison. Extracted so `defer colRows.Close()` covers
// every exit path (sqlclosecheck) — the inline form in the parent loop
// required two manual Close() sites.
func readSQLiteTableColumns(ctx context.Context, db *sql.DB, table string) ([]string, map[string]columnInfo, error) {
	colRows, err := db.QueryContext(ctx,
		`SELECT name, type, "notnull", dflt_value, pk FROM pragma_table_info(?) ORDER BY cid`, table)
	if err != nil {
		return nil, nil, err
	}
	defer colRows.Close()
	var cols []string
	info := map[string]columnInfo{}
	for colRows.Next() {
		var c, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := colRows.Scan(&c, &typ, &notnull, &dflt, &pk); err != nil {
			return nil, nil, err
		}
		cols = append(cols, c)
		// SQLite's pragma_table_info leaves `notnull` = 0 for a
		// PRIMARY KEY column even though the engine never allows a NULL
		// primary key value (this is documented SQLite behavior: PK
		// implies NOT NULL regardless of whether NOT NULL was spelled
		// out, but the pragma only reflects an *explicit* NOT NULL
		// clause). Treat any pk > 0 column as NOT NULL here so it lines
		// up with PostgreSQL's information_schema, which always reports
		// a PRIMARY KEY column as is_nullable = 'NO'.
		nullable := notnull == 0 && pk == 0
		info[normalizeColumnName(c)] = columnInfo{
			rawName:    c,
			dataType:   typ,
			nullable:   nullable,
			defaultVal: dflt.String,
		}
	}
	if err := colRows.Err(); err != nil {
		return nil, nil, err
	}
	return cols, info, nil
}

// readSQLiteIndexes lists index column-sets/uniqueness for one table via
// pragma_index_list + pragma_index_info. PRIMARY KEY-backed
// sqlite_autoindex_* entries are included: assertIndexesMatch compares
// by column-set/uniqueness, not name, so they line up against the
// PostgreSQL side's <table>_pkey index.
//
// One case pragma_index_list never reports: a single-column
// `INTEGER PRIMARY KEY` becomes a rowid alias, which SQLite implements
// via the table's own rowid rather than a separate index structure, so
// no sqlite_autoindex_* entry is created for it. PostgreSQL's
// equivalent (BIGSERIAL/INTEGER PRIMARY KEY, e.g. enrollment_events.id)
// always creates a real unique btree index. Synthesize the missing
// entry from pragma_table_info's pk flag so the two engines compare
// equal on this by-design difference in physical representation.
func readSQLiteIndexes(ctx context.Context, db *sql.DB, table string) ([]indexInfo, error) {
	idxRows, err := db.QueryContext(ctx,
		`SELECT name, "unique", partial FROM pragma_index_list(?)`, table)
	if err != nil {
		return nil, err
	}
	defer idxRows.Close()

	type rawIdx struct {
		name     string
		isUnique bool
		partial  bool
	}
	var raws []rawIdx
	for idxRows.Next() {
		var name string
		var isUnique, partial int
		if err := idxRows.Scan(&name, &isUnique, &partial); err != nil {
			return nil, err
		}
		raws = append(raws, rawIdx{name: name, isUnique: isUnique != 0, partial: partial != 0})
	}
	if err := idxRows.Err(); err != nil {
		return nil, err
	}

	var out []indexInfo
	sawIndexedPK := false
	for _, r := range raws {
		cols, err := readSQLiteIndexColumns(ctx, db, r.name)
		if err != nil {
			return nil, err
		}
		out = append(out, indexInfo{columns: cols, isUnique: r.isUnique, partial: r.partial})
	}

	pkCols, err := readSQLitePKColumns(ctx, db, table)
	if err != nil {
		return nil, err
	}
	if len(pkCols) > 0 {
		// If any existing index already covers exactly the PK
		// column-set (e.g. a composite PK, which DOES get a real
		// sqlite_autoindex), don't synthesize a duplicate.
		for _, idx := range out {
			if equalStringSlices(sortedCopy(idx.columns), sortedCopy(pkCols)) {
				sawIndexedPK = true
				break
			}
		}
		if !sawIndexedPK {
			out = append(out, indexInfo{columns: pkCols, isUnique: true, isPK: true})
		}
	}

	return out, nil
}

// readSQLitePKColumns returns the primary-key column names of a table in
// pk-ordinal order, via pragma_table_info's `pk` field (1-based rank,
// 0 = not part of the PK).
func readSQLitePKColumns(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	rows, err := db.QueryContext(ctx,
		`SELECT name FROM pragma_table_info(?) WHERE pk > 0 ORDER BY pk`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []string
	for rows.Next() {
		var c string
		if err := rows.Scan(&c); err != nil {
			return nil, err
		}
		cols = append(cols, c)
	}
	return cols, rows.Err()
}

// sortedCopy returns a sorted copy of s without mutating the input.
func sortedCopy(s []string) []string {
	out := append([]string(nil), s...)
	sort.Strings(out)
	return out
}

// readSQLiteIndexColumns lists the columns of one index via
// pragma_index_info, extracted for the same defer-per-call-site reason
// as readSQLiteTableColumns.
func readSQLiteIndexColumns(ctx context.Context, db *sql.DB, index string) ([]string, error) {
	colRows, err := db.QueryContext(ctx, `SELECT name FROM pragma_index_info(?)`, index)
	if err != nil {
		return nil, err
	}
	defer colRows.Close()
	var cols []string
	for colRows.Next() {
		var c string
		if err := colRows.Scan(&c); err != nil {
			return nil, err
		}
		cols = append(cols, c)
	}
	return cols, colRows.Err()
}

// extractSQLiteCheckExprs pulls every CHECK(...) body out of a CREATE
// TABLE statement with a balanced-paren scan (regexes cannot handle the
// nested parens inside IN-lists).
func extractSQLiteCheckExprs(createSQL string) []string {
	var out []string
	lower := strings.ToLower(createSQL)
	for i := 0; ; {
		idx := strings.Index(lower[i:], "check")
		if idx < 0 {
			break
		}
		pos := i + idx + len("check")
		for pos < len(createSQL) && (createSQL[pos] == ' ' || createSQL[pos] == '\t' || createSQL[pos] == '\n' || createSQL[pos] == '\r') {
			pos++
		}
		if pos >= len(createSQL) || createSQL[pos] != '(' {
			i = pos
			continue
		}
		depth, end := 0, -1
		for j := pos; j < len(createSQL) && end < 0; j++ {
			switch createSQL[j] {
			case '(':
				depth++
			case ')':
				depth--
				if depth == 0 {
					end = j
				}
			}
		}
		if end < 0 {
			break
		}
		out = append(out, createSQL[pos+1:end])
		i = end + 1
	}
	return out
}

// normalizeCheckExpr folds the dialects' CHECK spellings to one form:
// PG renders enums as `(status = ANY (ARRAY['a'::text, 'b'::text]))`,
// SQLite keeps the verbatim `status IN ('a', 'b')`. Lowercase, drop
// casts/quotes/brackets, rewrite `= any (array[...])` to `in (...)`,
// then strip ALL parens and collapse whitespace so only the token
// stream is compared.
func normalizeCheckExpr(expr string) string {
	s := strings.ToLower(expr)
	s = strings.TrimPrefix(strings.TrimSpace(s), "check ")
	s = strings.ReplaceAll(s, "::text", "")
	s = strings.ReplaceAll(s, "= any (array[", "in (")
	s = strings.ReplaceAll(s, "= any(array[", "in (")
	for _, ch := range []string{"(", ")", "[", "]", `"`, "'", "`", ","} {
		s = strings.ReplaceAll(s, ch, " ")
	}
	return strings.Join(strings.Fields(s), " ")
}

// sqliteBooleanCheckRE matches SQLite's BOOLEAN-emulation guard
// (`col IN (0, 1)` after normalization). PG uses a real BOOLEAN type,
// so these checks are engine-inherent and excluded from parity.
var sqliteBooleanCheckRE = regexp.MustCompile(`^[a-z0-9_]+ in 0 1$`)

// sqliteJSONValidCheckRE matches SQLite's json_valid(...) CHECK guards
// added by 0052_json_valid_checks.sql (M3). SQLite has no JSONB type, so
// these CHECKs are the compensating control for what PostgreSQL's native
// JSONB column type already enforces at write time — there is no PG-side
// CHECK constraint to match because the type system does the job, so
// these are engine-inherent and excluded from parity. The pattern also
// matches the permissive `col = ” or json_valid(col)` form used for
// jobs.payload_json, where ” is a legitimate empty-payload sentinel.
//
// This pattern also happens to match integration_providers.config's
// permissive `json_valid(config) OR config LIKE 'PVS_:%'` SQLite CHECK,
// which is harmless — see pvsSealedJSONCheckRE below for the reason that
// column needs its OWN, more tightly scoped pattern to also exclude
// PostgreSQL's counterpart CHECK (which does not contain the literal
// substring "json_valid" and so would never match here).
var sqliteJSONValidCheckRE = regexp.MustCompile(`json_valid`)

// pvsSealedJSONCheckRE matches the "plain JSON OR vault-sealed PVSn:
// ciphertext" compensating control that exists identically in spirit on
// BOTH engines for integration_providers.config (bug1/H-6):
//
//   - SQLite: `json_valid(config) OR config LIKE 'PVS_:%'`
//     (db/migrations/sqlite/0052_json_valid_checks.sql), normalized to
//     "json_valid config or config like pvs_:%".
//   - PostgreSQL: `config LIKE 'PVS_:%' OR config IS JSON`
//     (db/migrations/postgres/0052_integration_providers_config_text.sql),
//     normalized to "config ~~ pvs_:% or config is json" — `~~` is
//     Postgres's internal LIKE operator token, which normalizeCheckExpr
//     does not rewrite (unlike the `= any (array[...])` enum idiom it
//     does fold), so `~~` survives normalization verbatim.
//
// Neither side has a matching CHECK on the other engine's information
// schema (PostgreSQL's validation comes from its former JSONB type,
// SQLite's from json_valid()), so without this exclusion the schema-sync
// comparator would flag one side's CHECK as "only in PostgreSQL"/"only in
// SQLite" even though both enforce the identical compensating control.
// The pattern requires BOTH the PVS-prefix fragment AND a JSON-validation
// idiom (json_valid or "is json") in the SAME normalized expression — not
// just "any is json check" — so an unrelated future column that happens
// to use `IS JSON` for a different reason is not silently exempted from
// CHECK parity.
var pvsSealedJSONCheckRE = regexp.MustCompile(`pvs_:%`)

// jsonValidationIdiomRE matches either engine's "this string is valid
// JSON" predicate after normalizeCheckExpr: SQLite's json_valid(...) call
// or PostgreSQL's IS JSON predicate (normalizes to "is json" — see
// normalizeCheckExpr's `::text`/paren-stripping, which leaves the two
// keywords space-separated).
var jsonValidationIdiomRE = regexp.MustCompile(`json_valid|is json`)

// isEngineInherentCheck reports whether a normalized CHECK expression is
// one of the engine-inherent compensating controls that intentionally has
// no counterpart CHECK constraint on the other engine, and so must be
// excluded from CHECK-expression parity rather than reported as
// only-in-one-engine drift. Applied on BOTH read paths (readPostgresSchema
// and readSQLiteSchema) — previously only readSQLiteSchema filtered checks
// through this function, which was a latent gap: a PG CHECK matching one
// of these patterns would still have unconditionally been asserted
// against SQLite. That gap only became load-bearing once PostgreSQL
// gained its own inherent CHECK (the IS JSON pair introduced by
// pvsSealedJSONCheckRE); the boolean-emulation pattern
// (sqliteBooleanCheckRE) only ever appears on the SQLite side in
// practice, so filtering it on the PG path too is a no-op today but
// keeps the function's contract symmetric and correct if that ever
// changes.
func isEngineInherentCheck(normalized string) bool {
	if sqliteBooleanCheckRE.MatchString(normalized) {
		return true
	}
	if sqliteJSONValidCheckRE.MatchString(normalized) {
		return true
	}
	if pvsSealedJSONCheckRE.MatchString(normalized) && jsonValidationIdiomRE.MatchString(normalized) {
		return true
	}
	return false
}

// normalizeFK renders one FK as "column->ref_table [RULE]". Column
// names go through the same timestamp-suffix folding as the column
// comparison (_unix then _at); delete rules are upper-cased
// ("NO ACTION" both sides).
func normalizeFK(column, refTable, rule string) string {
	col := strings.TrimSuffix(strings.TrimSuffix(strings.ToLower(column), "_unix"), "_at")
	return fmt.Sprintf("%s->%s [%s]", col, strings.ToLower(refTable), strings.ToUpper(strings.TrimSpace(rule)))
}

func diffSlices(a, b []string) []string {
	set := map[string]struct{}{}
	for _, x := range b {
		set[strings.ToLower(x)] = struct{}{}
	}
	var only []string
	for _, x := range a {
		if _, ok := set[strings.ToLower(x)]; !ok {
			only = append(only, x)
		}
	}
	return only
}
