/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 OK when the HTTP server is accepting connections.
         *     Plain `text/plain` body containing the literal string `ok` —
         *     kept text rather than JSON so kubelet's default probe parser
         *     doesn't have to recurse JSON.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Panel build identification
         * @description Returns the running panel's build metadata. Operator+ callers
         *     also get `commit_sha` and `build_time`; viewer-role responses
         *     carry only `version`.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Build metadata for the running control-plane process. */
        VersionResponse: {
            /**
             * @description Semantic version (or "dev" for unstamped builds).
             * @example 1.4.7
             */
            version: string;
            /** @description Git commit hash baked in at build time. Operator+ only. */
            commit_sha?: string;
            /**
             * Format: date-time
             * @description RFC3339 build timestamp. Operator+ only.
             */
            build_time?: string;
        };
        /** @description Standard error envelope used by every 4xx / 5xx response. */
        Error: {
            /** @description Machine-readable error code (e.g. `not_found`, `forbidden`). */
            error: string;
            /** @description Human-readable message; safe to display to operators. */
            message?: string;
            /** @description Optional structured context. Shape varies per error code. */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Panel build info. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Unauthenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
