// Package sqlitebaseline exposes the consolidated baseline_v1.sql
// schema as an embed.FS, separate from the per-version migration FS
// so goose's filename version-parser doesn't trip over the
// non-numbered baseline file.
//
// Generated by migrate.TestRegenerateSQLiteBaseline. See
// docs/superpowers/plans/2026-05-09-baseline-migration.md for the
// freeze rationale.
package sqlitebaseline

import "embed"

//go:embed *.sql
var FS embed.FS

// LatestVersion is the migration version represented by the baseline.
// Fresh installs apply baseline_v1.sql and mark versions 1..LatestVersion
// as already applied in goose_db_version; goose.Up then only runs
// migrations > LatestVersion. Bump this constant whenever
// TestRegenerateSQLiteBaseline writes a new file.
const LatestVersion = 53
